<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.146">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>GeneralAnalysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="GeneralAnalysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="GeneralAnalysis_files/libs/quarto-html/quarto.js"></script>
<script src="GeneralAnalysis_files/libs/quarto-html/popper.min.js"></script>
<script src="GeneralAnalysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="GeneralAnalysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="GeneralAnalysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="GeneralAnalysis_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="GeneralAnalysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="GeneralAnalysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="GeneralAnalysis_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="GeneralAnalysis_files/libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="GeneralAnalysis_files/libs/d3-4.5.0/d3.min.js"></script>
<script src="GeneralAnalysis_files/libs/sankey-1/sankey.js"></script>
<script src="GeneralAnalysis_files/libs/sankeyNetwork-binding-0.4/sankeyNetwork.js"></script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">GeneralAnalysis</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="about-the-data" class="level2">
<h2 class="anchored" data-anchor-id="about-the-data">About the data</h2>
<p>The dataset, scraped from <a href="http://nemesis555nchzn2dogee6mlc7xxgeeshqirmh3yzn4lo5cnd4s5a4yd.onion/">Nemesis</a> between 1<sup>st</sup> January to 11<sup>th</sup> January, contains 1334 files comprising 607 posts on drug sales, 415 posts on fraud, 134 posts providing guides and tutorials on illegal activities, and other miscellaneous posts. In this analysis, we will focus solely on the drug sales-related posts.</p>
<p>As the original documents were in text format, which made it difficult to carry out quantitative analysis, I cleaned the data and put them into a data frame. I then saved the data frame as a CSV file named “complete.csv”.</p>
</section>
<section id="the-payment-method" class="level2">
<h2 class="anchored" data-anchor-id="the-payment-method">The payment method</h2>
<p><strong>Bitcoin and Monero accepted.</strong> All items are listed as an <strong>escrow</strong>. The order process is as follows:</p>
<ul>
<li>After the buyer has placed an order, the vendor has 5 days to accept or reject the order.</li>
<li>The buyer will get a full refund if the vendor doesn’t accept the order within 5 days.</li>
<li>If the buyer doesn’t want to wait 5 days, there will be a cancel button after 48 hours to cancel the order and get a full refund.</li>
<li>After the order got accepted, the vendor has 5 days to send it. The buyer can not cancel the order at this point.</li>
<li>The buyer will get a full refund if the vendor doesn’t send the order within 5 days.</li>
<li>The buyer has 3 days to open a dispute if the order does not match the description.</li>
<li>After the order got finalized, the buyer can leave a review.</li>
<li>If you have any questions, leave a comment or create a post on our forum.</li>
</ul>
</section>
<section id="load-packages-and-data" class="level2">
<h2 class="anchored" data-anchor-id="load-packages-and-data">Load Packages and data</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forcats)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidytext)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraph)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggraph)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(geosphere)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(countrycode)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rnaturalearth)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rnaturalearthdata)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lwgeom)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggsankey)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(networkD3)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>data  <span class="ot">&lt;-</span>  <span class="fu">read_csv</span>(<span class="st">"/Users/shihaitao/Documents/DarknetProject/Nemesis/complete.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="the-number-of-posts-of-each-type-of-drugs-top20" class="level2">
<h2 class="anchored" data-anchor-id="the-number-of-posts-of-each-type-of-drugs-top20">The number of posts of each type of drugs (Top20)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Drug_Type) <span class="sc">%&gt;%</span> </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">separate</span>(Drug_Type, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"Drug_Type"</span>, <span class="st">"Drug_Sub"</span>), <span class="at">sep =</span> <span class="st">"  » "</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(count)) <span class="sc">%&gt;%</span> </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(.,<span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 3
   Drug_Type               Drug_Sub               count
   &lt;chr&gt;                   &lt;chr&gt;                  &lt;int&gt;
 1 Cannabis                Buds and Flowers         103
 2 Dissociatives           Ketamine                  60
 3 Ecstasy                 XTC Pills                 42
 4 Steroids                &lt;NA&gt;                      32
 5 Stimulants              Cocaine                   32
 6 Prescription Drugs      &lt;NA&gt;                      29
 7 Stimulants              Amphetamine/Speed         29
 8 Opioids                 Oxycodone                 23
 9 Opioids                 Heroin                    20
10 Psychedelics            LSD                       20
11 Benzodiazepine (Benzos) Pills                     16
12 Stimulants              Adderall                  15
13 Stimulants              Methamphetamine (Meth)    15
14 Cannabis                Hash                      14
15 Benzodiazepine (Benzos) Diazepam (Valium)         13
16 Ecstasy                 MDMA                      13
17 Benzodiazepine (Benzos) Alprazolam (Xanax)         9
18 Psychedelics            DMT                        9
19 Cannabis                Shake                      8
20 Benzodiazepine (Benzos) Powder                     7</code></pre>
</div>
</div>
<p>Different types of drug are sold in Nemesis, namely, Cannabis, Dissociatives, Opioids, Steroids, Psychedelics, Stimulants, Prescription Drugs, Benzodiazepine (Benzos), Ecstasy, and others. Some drug type has specific subcategories associated with it. For example, under the drug type Cannabis, the subcategories include Buds and Flowers, Hash, and Shake. The “count” column represents the number of posts for each drug subcategory, indicating the frequency or popularity of each drug subcategory. For instance, the drug subcategory “Buds and Flowers” has a count of 103, and it has the highest number of posts among all the drug subcategories listed. Dissociatives (Ketamine), Ecstasy (XTC Pills), Steroids, and Stimulants (Cocaine, Amphetamine/Speed) also have significant counts, suggesting their popularity in the market.</p>
</section>
<section id="the-number-of-posts-of-each-drug-top20" class="level2">
<h2 class="anchored" data-anchor-id="the-number-of-posts-of-each-drug-top20">The number of posts of each drug (Top20)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#capitalise all the drug names and count </span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>DrugName <span class="ot">&lt;-</span> <span class="fu">toupper</span>(data<span class="sc">$</span>DrugName)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>item_counts <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(DrugName) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(count))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(item_counts, <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 2
   DrugName                                    count
   &lt;chr&gt;                                       &lt;int&gt;
 1 LSD                                            14
 2 HEROIN                                          9
 3 GORILLA GLUE                                    7
 4 RACEMIC KETAMINE                                7
 5 XANAX                                           7
 6 ADDERALL                                        6
 7 COKE                                            6
 8 KETAMINE S-ISOMER SUGAR                         6
 9 MDMA                                            6
10 OXYCODONE                                       6
11 SPEED PASTE                                     6
12 AMPHETAMINE PASTE                               5
13 CANNALOPE HAZE                                  5
14 COLOMBIAN COCAINE                               5
15 KETAMINE                                        5
16 KETAMINE-NEEDLES                                5
17 S-ISOMERE KETAMINE                              5
18 CLONAZEPAM                                      4
19 ORIGINAL LA PAZ, BOLIVIAN UNCUT RAW COCAINE     4
20 SOUR DIESEL                                     4</code></pre>
</div>
</div>
<p>The data frame consists of the top 20 drug names mentioned in posts. The “count” column represents the number of posts for each drug. It can partly indicate the popularity of each drug. Based on the counts, we can see that LSD (n=14), Heroin (n=9), Gorilla Glue (n=7), Racemic Ketamine (n=7), and Xanax (n=7) have relatively higher counts, suggesting a higher level of discussion or interest in these drugs.</p>
</section>
<section id="the-brand-name-of-the-drugs-for-sale" class="level2">
<h2 class="anchored" data-anchor-id="the-brand-name-of-the-drugs-for-sale">The brand name of the drugs for sale</h2>
<p>The table below shows each brand name and its number of occurrences, and it can be observed that MONSTERLAB and HYDROGURU are the brands with the highest number of occurrences. These two brands are not specific to any particular drug, but rather the names of the dealers. It seems that they have generated a certain brand effect, representing a guarantee of high-quality drugs.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>BrandName <span class="ot">&lt;-</span> <span class="fu">toupper</span>(data<span class="sc">$</span>BrandName) </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>BrandName_Re_NA <span class="ot">&lt;-</span> data<span class="sc">$</span>BrandName[<span class="sc">!</span><span class="fu">is.na</span>(data<span class="sc">$</span>BrandName)] <span class="co">#remove NA</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>brand_counts <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">table</span>(BrandName_Re_NA))</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(brand_counts) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"BrandName"</span>, <span class="st">"Count"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>brand_counts <span class="ot">&lt;-</span> brand_counts <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(Count))</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>brand_counts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 81 × 2
   BrandName     Count
   &lt;chr&gt;         &lt;int&gt;
 1 MONSTERLAB       21
 2 HYDROGURU        13
 3 CENFORCE          5
 4 BLUE PUNISHER     4
 5 KAMAGRA           4
 6 PFIZER            4
 7 VIDALISTA         4
 8 KETALAR           3
 9 MASERATI          3
10 PERCOCET          3
# ℹ 71 more rows</code></pre>
</div>
</div>
<section id="the-brand-name-of-xtc-pills" class="level3">
<h3 class="anchored" data-anchor-id="the-brand-name-of-xtc-pills">The brand name of XTC Pills</h3>
<p>Another interesting observation is that the brand name of XTC Pills may indicate the strength or purity of these drugs and also provide a guarantee of quality for buyers. For instance, ORANGE TESLA with the warning “strong, be careful!” (01025.txt) may harbour more potential strength compared to Pink Glitter Tesla, with the description “very clean and stimulating” (00307.txt). While almost all vendors selling XTC Pills highlight the “high quality” of their products, some emphasise that their XTC Pills have been “lab tested” (13 out of 42 posts) or “black light tested and reagent tested with Marquis and Froehd” (00458 and 01025). Such measures in place serve the primary role of ensuring top-notch quality and utmost safety.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Drug_Type <span class="sc">==</span> <span class="st">"Ecstasy  » XTC Pills"</span><span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(BrandName)) <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Drug_Type, BrandName) <span class="sc">%&gt;%</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 2
   Drug_Type            BrandName         
   &lt;chr&gt;                &lt;chr&gt;             
 1 Ecstasy  » XTC Pills BLUE PUNISHERS    
 2 Ecstasy  » XTC Pills PINK GLITTER TESLA
 3 Ecstasy  » XTC Pills PUNISHER          
 4 Ecstasy  » XTC Pills UFO               
 5 Ecstasy  » XTC Pills SUPERMAN          
 6 Ecstasy  » XTC Pills ORANGE TESLA      
 7 Ecstasy  » XTC Pills POKEMON           
 8 Ecstasy  » XTC Pills BLUE PUNISHER     
 9 Ecstasy  » XTC Pills HYDROGURU         
10 Ecstasy  » XTC Pills AUDI              
11 Ecstasy  » XTC Pills PANAMA            
12 Ecstasy  » XTC Pills TESLA             
13 Ecstasy  » XTC Pills SKULL FACE        
14 Ecstasy  » XTC Pills MB SKULL CANDY    
15 Ecstasy  » XTC Pills LOUIS VUITTON     
16 Ecstasy  » XTC Pills PURPLE DOMINO     
17 Ecstasy  » XTC Pills MASERATI          
18 Ecstasy  » XTC Pills FANTA             </code></pre>
</div>
</div>
</section>
<section id="the-availibility-rate" class="level3">
<h3 class="anchored" data-anchor-id="the-availibility-rate">The availibility rate</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(data<span class="sc">$</span>Availablity <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9587459</code></pre>
</div>
</div>
<p>It is worth mentioning that not all drugs available on the market are actually available on Nemesis Market. According to the dataset provided, the availability rate of drugs on the Nemesis Market is 95.87%. This may be due to reasons such as the drug being sold out or the drug vendors being on holiday.</p>
</section>
</section>
<section id="rating-reviews-and-sales" class="level2">
<h2 class="anchored" data-anchor-id="rating-reviews-and-sales">Rating, Reviews and Sales</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Get the Rating number from strings</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Rating <span class="ot">&lt;-</span> data<span class="sc">$</span>Rating <span class="sc">%&gt;%</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_extract</span>(<span class="st">"</span><span class="sc">\\</span><span class="st">d+(</span><span class="sc">\\</span><span class="st">.</span><span class="sc">\\</span><span class="st">d+)?"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.numeric</span>()</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Select the columns that we need</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>data_RRS <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">select</span>(DrugName,Drug_Type,Vendor_Name, Rating,Reviews,Sales)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>data_RRS <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Sales<span class="sc">==</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 127 × 6
   DrugName               Drug_Type             Vendor_Name Rating Reviews Sales
   &lt;chr&gt;                  &lt;chr&gt;                 &lt;chr&gt;        &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 RACEMIC KETAMINE       Dissociatives  » Ket… commission…      0       0     0
 2 NEEDLE KETAMINE        Dissociatives  » Ket… cocainecar…      0       0     0
 3 LIDOCAINE              Stimulants  » Lidoca… TreasureCr…      0       0     0
 4 SGT-263                Cannabis  » Syntheti… TreasureCr…      0       0     0
 5 4-MEO-PCP              Dissociatives  » Met… TreasureCr…      0       0     0
 6 METHOXPROPAMINE        Dissociatives  » Met… TreasureCr…      0       0     0
 7 MOTHOXPROPAMINE        Dissociatives  » Met… TreasureCr…      0       0     0
 8 RACEMIC KETAMINE       Dissociatives  » Ket… commission…      0       0     0
 9 METHAMPHETAMINE (METH) Stimulants  » Metham… TreasureCr…      0       0     0
10 OXYCODONE              Opioids  » Oxycodone  STUNNAGANG       0       0     0
# ℹ 117 more rows</code></pre>
</div>
</div>
<p>127 drugs have never been sold, so it would be better to remove them before analysing the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>data_RRS_noZero <span class="ot">&lt;-</span> data_RRS <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Sales<span class="sc">!=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="lets-see-the-statistical-information-about-ratings-reviews-and-sales." class="level3">
<h3 class="anchored" data-anchor-id="lets-see-the-statistical-information-about-ratings-reviews-and-sales.">Let’s see the statistical information about ratings, reviews, and sales.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data_RRS_noZero[, <span class="fu">c</span>(<span class="st">"Rating"</span>, <span class="st">"Reviews"</span>, <span class="st">"Sales"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Rating         Reviews           Sales      
 Min.   :0.000   Min.   :   0.0   Min.   :    1  
 1st Qu.:4.700   1st Qu.:  33.0   1st Qu.:   42  
 Median :4.900   Median : 112.0   Median :  377  
 Mean   :4.789   Mean   : 449.2   Mean   : 1874  
 3rd Qu.:5.000   3rd Qu.: 514.0   3rd Qu.: 1250  
 Max.   :5.000   Max.   :5356.0   Max.   :19712  </code></pre>
</div>
</div>
</section>
<section id="grouped-summary-statistics-calculate-summary-statistics-for-each-type-of-drug." class="level3">
<h3 class="anchored" data-anchor-id="grouped-summary-statistics-calculate-summary-statistics-for-each-type-of-drug.">Grouped summary statistics: Calculate summary statistics for each type of drug.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>group_Drug_Type <span class="ot">&lt;-</span> data_RRS_noZero <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Drug_Type) <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_rating =</span> <span class="fu">mean</span>(Rating),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">total_reviews =</span> <span class="fu">sum</span>(Reviews),</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">toal_sales =</span> <span class="fu">sum</span>(Sales))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Best-selling drug types (top 20)</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>group_Drug_Type <span class="sc">%&gt;%</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(toal_sales)) <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">20</span>)<span class="sc">%&gt;%</span> <span class="fu">select</span>(Drug_Type,toal_sales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 2
   Drug_Type                                     toal_sales
   &lt;chr&gt;                                              &lt;dbl&gt;
 1 Cannabis  » Buds and Flowers                      133324
 2 Cannabis  » Hash                                   73373
 3 Dissociatives  » Ketamine                          64675
 4 Ecstasy  » XTC Pills                               56542
 5 Cannabis  » Shake                                  50787
 6 Psychedelics  » LSD                                47496
 7 Stimulants  » Amphetamine/Speed                    47155
 8 Opioids  » Other                                   33209
 9 Opioids  » Fentanyl                                32956
10 Benzodiazepine (Benzos)  » Diazepam (Valium)       30997
11 Prescription Drugs                                 29243
12 Cannabis  » Concentrates                           28987
13 Opioids  » Codeine                                 25898
14 Opioids  » Heroin                                  22239
15 Ecstasy  » MDMA                                    21664
16 Stimulants  » Cocaine                              19789
17 Opioids  » Oxycodone                               19668
18 Benzodiazepine (Benzos)  » Alprazolam (Xanax)      18635
19 Benzodiazepine (Benzos)  » Pills                   17248
20 Stimulants  » Methamphetamine (Meth)               14298</code></pre>
</div>
</div>
<p><strong>Highest rated drug types (top 20)</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>group_Drug_Type <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(mean_rating)) <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">20</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(Drug_Type, mean_rating)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 2
   Drug_Type                            mean_rating
   &lt;chr&gt;                                      &lt;dbl&gt;
 1 Benzodiazepine (Benzos)  » Powder           5   
 2 Benzodiazepine (Benzos)  » RCs              5   
 3 Benzodiazepine (Benzos)  » Zopiclone        5   
 4 Dissociatives  » Methoxetamine (MXE)        5   
 5 Opioids  » Codeine                          5   
 6 Opioids  » Codeine Syrups/Solutions         5   
 7 Opioids  » Dihydrocodeine                   5   
 8 Opioids  » Hydrocodone                      5   
 9 Opioids  » Hydromorphone                    5   
10 Opioids  » Opium                            5   
11 Stimulants  » Mephedrone                    5   
12 Weight Loss                                 5   
13 Prescription Drugs                          4.99
14 Steroids                                    4.98
15 Benzodiazepine (Benzos)  » Pills            4.93
16 Cannabis  » Concentrates                    4.93
17 Cannabis  » Shake                           4.9 
18 Psychedelics  » Other                       4.9 
19 Stimulants  » Methylphenidate               4.9 
20 Cannabis  » Buds and Flowers                4.88</code></pre>
</div>
</div>
<p><strong>Types of drugs that get the most reviews (top 20)</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>group_Drug_Type <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(total_reviews)) <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">20</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(Drug_Type, total_reviews)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 2
   Drug_Type                                    total_reviews
   &lt;chr&gt;                                                &lt;dbl&gt;
 1 Cannabis  » Buds and Flowers                         41887
 2 Prescription Drugs                                   13902
 3 Stimulants  » Cocaine                                12982
 4 Benzodiazepine (Benzos)  » Diazepam (Valium)         12595
 5 Dissociatives  » Ketamine                            11888
 6 Opioids  » Codeine                                   10704
 7 Ecstasy  » XTC Pills                                 10147
 8 Cannabis  » Hash                                      9740
 9 Cannabis  » Concentrates                              8411
10 Psychedelics  » LSD                                   8253
11 Opioids  » Oxycodone                                  8187
12 Stimulants  » Amphetamine/Speed                       7897
13 Opioids  » Tramadol                                   5371
14 Benzodiazepine (Benzos)  » Zopiclone                  5356
15 Opioids  » Dihydrocodeine                             5356
16 Opioids  » Heroin                                     5129
17 Cannabis  » Shake                                     4241
18 Steroids                                              3558
19 Stimulants  » Methamphetamine (Meth)                  3482
20 Stimulants  » Adderall                                2674</code></pre>
</div>
</div>
</section>
<section id="grouped-summary-statistics-calculate-summary-statistics-for-vendors." class="level3">
<h3 class="anchored" data-anchor-id="grouped-summary-statistics-calculate-summary-statistics-for-vendors.">Grouped summary statistics: Calculate summary statistics for Vendors.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>group_Vendor <span class="ot">&lt;-</span> data_RRS_noZero <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Vendor_Name) <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_reviews =</span> <span class="fu">sum</span>(Reviews),</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">total_sales =</span> <span class="fu">sum</span>(Sales))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Top 10 vendors based on sales</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>group_Vendor <span class="sc">%&gt;%</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_sales)) <span class="sc">%&gt;%</span> </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Vendor_Name,total_sales) <span class="sc">%&gt;%</span> </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   Vendor_Name     total_sales
   &lt;chr&gt;                 &lt;dbl&gt;
 1 SocialPharma         103577
 2 maurelius            101537
 3 MicroDroper           65912
 4 queenofcannabis       58002
 5 PingPongUK            44556
 6 discover              44148
 7 DrRelax               40992
 8 TorDrug               39424
 9 drugstar              36168
10 straightfromnl        35666</code></pre>
</div>
</div>
<p><strong>Bottom 10 vendors (excluding those who never sold anything) based on sales</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>group_Vendor <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_sales)) <span class="sc">%&gt;%</span> </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Vendor_Name,total_sales) <span class="sc">%&gt;%</span> </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tail</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   Vendor_Name    total_sales
   &lt;chr&gt;                &lt;dbl&gt;
 1 yodiweed                 5
 2 BSPLLC                   3
 3 kings                    3
 4 shinyflakes              3
 5 OliverTwiztt             2
 6 POPEYE_GERMANY           2
 7 DoctorPotenz             1
 8 Grüneapotheke            1
 9 Replicagod               1
10 UKnarcotics              1</code></pre>
</div>
</div>
<p>By comparing sales figures, we can identify that the top 10 sellers are SocialPharma (103577), maurelius(101537), MicroDroper(65912), queenofcannabis(58002), PingPongUK(44556), discover(44148), DrRelax(40992), TorDrug(39424), drugstar(36168), and straightfromnl(35666). The numbers in the parenthesis are sales on this platform. On the other hand, yodiweed(5), BSPLLC(3), kings(3), shinyflakes(3), OliverTwiztt(2), POPEYE_GERMANY(2), DoctorPotenz(1), Grüneapotheke(1), Replicagod(1), UKnarcotics(1) are the newcomers or less established sellers.</p>
<p>We can further examine their advertising, returns policies, and self-introductions to understand why some sellers’ products are more popular and in what ways they gain the trust of buyers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Vendor_Name<span class="sc">==</span><span class="st">"SocialPharma"</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(File_Name, Drug_Type, MainContent,Refund,Review))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The highest-selling vendor is called SocialPharma (filename: 00132, 00373, 00483, 00519, 00520, 00721, 00923, 01107), and they primarily sell two types of drugs, namely Benzodiazepine (Benzos) and Opioids. Only Oxycodone is shipped from the United Kingdom to worldwide destinations, and it is marked as “non-refundable/non-reshipable.” The other products he sells, namely Zopiclone, Diazepam (Valium), Dihydrocodeine, Codeine, and Tramadol, are sold locally in the UK and have corresponding return and exchange policies. The vendor is a self-employed because he always refers to himself with “me” instead of “us”.</p>
<p>Surprisingly, his drug descriptions are often limited to just two lines, specifying the quantity and strength, without mentioning the quality of the products. Similarly, his return and exchange policies are quite brief. He offers either a reshipment or a 50% refund based on the buyer’s purchase time and his own perception of the buyer’s trustworthiness.</p>
<p>Therefore, we can assume that the trust generated by the high ratings (all five stars) and a large number of reviews no longer requires him to go through the trouble of describing the product and building trust. In a way, the rating system and sales data have established trust that surpasses the need for product descriptions themselves. Another explanation could be attributed to the types of drugs they sell. Most of these drugs are sold in tablets, which gives limited room for detailed descriptions. This is in stark contrast to vendors selling Cannabis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Vendor_Name<span class="sc">==</span><span class="st">"maurelius"</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(File_Name, Drug_Type, MainContent,Refund,Review))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The second-largest vendor in terms of sales is named Maurelius (Filenames: 00028, 00137, 00497, 00498, 00544, 00550, 00553, 00554, 01168, 01170, 01206, 01227, 01240, 01249, 01250, 01253). They specialize in selling Cannabis (Shake, Hash, and Buds and Flowers) with detailed descriptions. <strong>Tetrahydrocannabinol (THC)</strong> level is generally provided as an indicator for potency. Numerous paragraphs are dedicated to describing the aroma and taste of each Cannabis product. For example, when describing Afghan Kush, the aroma and taste of this strain are mentioned three times.</p>
<blockquote class="blockquote">
<p>The aroma of this medical marijuana strain will be like a mango orange farm with a pinch of funky odor. The taste of this strain is not at all harsh. This will have a bland and fruity taste. (01253, Pos. 35-37)</p>
</blockquote>
<blockquote class="blockquote">
<p>Flavors<br>
Herbal, Pine, Spicy, Sweet, Woody<br>
Aromas<br>
Earthy, Floral, Kush, Pungent, Spicy, Sweet (01253, Pos. 47-50)</p>
</blockquote>
<blockquote class="blockquote">
<p>Aroma</p>
<p>As is the case with pretty much every single strain from the Hindu Kush mountain range, the primary aroma of the Afghan Kush strain is one of hash.</p>
<p>Dense, powdery, and just a little bit spicy, this strain smells like walking into a familiar and friendly hash pipe shop in the Middle East or West India.</p>
<p>There is sweetness there, but the overwhelming characteristic of the aroma is one of dankness and pleasant hash.</p>
<p>Flavor</p>
<p>The overwhelming quality of the taste of the Afghan Kush smoke is one of sweet hash. It is pretty similar to its aroma, though, with a few key differences that help set it apart.</p>
<p>Instead of the intense spiciness that you’d expect after walking nearby any Afghan Kush bud, the leading quality is one of dank hash. As soon as it hits your tongue, you feel almost overpowered by the taste of hashish.</p>
<p>In a way, Afghan Kush tastes like a real marijuana experience – that quintessential flavor quality that makes smoking marijuana what it is. (01253, Pos. 85-100)</p>
</blockquote>
<p>Furthermore, the heritage/hybrid of Cannabis is also an important aspect that vendors want to emphasise to highlight the rarity and effects of their products. For example:</p>
<blockquote class="blockquote">
<p>Alien Cookies is an evenly balanced hybrid (50% sativa/50% indica) strain created through a cross of the popular Alien Dawg X Girl Scout Cookies strains. This bud is incredibly rare to find, but totally worth it every time because of its flawless combination of its parents’ effects. (01240, Pos. 27-30)</p>
</blockquote>
<p>The effects of different drugs on the body reveals several patterns:</p>
<ol type="1">
<li>Social Behavior and Creativity: Individuals who seek these drugs for their psychotropic effects may seek to experience heightened sociability, amplified ethusiasm and to facilitate creative endeavors.</li>
<li>Euphoria and Blissful Sensations: These effects may contribute to a sense of happiness, cheerfulness, and laughter, thereby attracting individuals seeking positive emotional experiences.</li>
<li>Relaxation and Body Buzz: This combination of physical relaxation and elevated mood may be appealing to individuals seeking stress relief, tranquility, and a soothing experience.</li>
<li>Medicinal Benefits: Individuals may turn to these drugs for potential therapeutic effects.</li>
<li>Sleep and Sedation: Some individuals may seek these drugs to aid with sleep-related issues or relaxation before bedtime.</li>
</ol>
<p><strong>Other ways to attract purchase:</strong></p>
<ol type="1">
<li><p>Being frankly about the side effects: while dry mouth and dry eyes are often mentioned in the posts, medical adverse reactions are listed. For example,</p>
<blockquote class="blockquote">
<p>ADVERSE REACTIONS: Dry mouth, Dry eyes<br>
MEDICAL Depression, Insomnia, Stress, Cramps, Fatigue (00498, Pos. 59-60)</p>
</blockquote>
<p>By providing honest and transparent information about the side effects and dangers of drugs, vendors can, to some extent, build trust. Potential users may be more inclined to work with vendors who are concerned about user safety. Vendors may feel that they have an ethical responsibility to provide accurate information to potential users to ensure that users are able to make informed decisions.</p></li>
<li><p>The minimal negative side effects: for example, the vendor points out that Amnesia Haze is a sativa strain with minimal negative side effects compared to other sativa strains, as it doesn’t induce dizziness, paranoia, anxiety, or nausea. The main drawback of Amnesia Haze is dry mouth (cotton mouth), which can be alleviated by staying hydrated before, during, and after cannabis consumption. (see 00497, Pos. 92-101)</p></li>
</ol>
<blockquote class="blockquote">
<p>Refund Policy: “If your order doesn’t show up we can offer you 50% reship or refund of the original order. For years we used to reship 100% of the orders but unfortunately we live in a world where people take advantage of you and sometimes our clients lie when it comes to receiving orders. Please understand that we are here for money and we feel sorry that honnest men/women have to suffer the loss. Besides, you are buying weed, not vegetables. :)”</p>
</blockquote>
</section>
<section id="bar-plot-of-average-rating-per-drug_type" class="level3">
<h3 class="anchored" data-anchor-id="bar-plot-of-average-rating-per-drug_type">Bar plot of average rating per Drug_Type:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>data_RRS_noZero <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Drug_Type) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_rating =</span> <span class="fu">mean</span>(Rating)) <span class="sc">%&gt;%</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(mean_rating) <span class="sc">%&gt;%</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Drug_Type, mean_rating), <span class="at">y =</span> mean_rating, <span class="at">fill =</span> Drug_Type)) <span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Drug_Type, mean_rating), <span class="at">y =</span> mean_rating, <span class="at">label =</span> <span class="fu">round</span>(mean_rating, <span class="dv">2</span>)), <span class="at">vjust =</span> <span class="fl">0.6</span>, <span class="at">hjust=</span><span class="dv">0</span>,<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add geom_text to display value labels</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average Rating per Drug Type"</span>, <span class="at">y =</span> <span class="st">"Average Rating"</span>, <span class="at">x =</span> <span class="st">"Drug Type"</span>) <span class="sc">+</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>, <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>)) <span class="sc">+</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="GeneralAnalysis_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="scatter-plot-of-sales-vs.-review" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plot-of-sales-vs.-review">Scatter plot of Sales vs.&nbsp;Review</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_RRS_noZero, <span class="fu">aes</span>(<span class="at">x =</span> Reviews, <span class="at">y =</span> Sales)) <span class="sc">+</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Sales vs. Reviews"</span>, <span class="at">x =</span> <span class="st">"Reviews"</span>, <span class="at">y =</span> <span class="st">"Sales"</span>) <span class="sc">+</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="GeneralAnalysis_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="correlation" class="level3">
<h3 class="anchored" data-anchor-id="correlation">correlation</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(data_RRS_noZero[, <span class="fu">c</span>(<span class="st">"Rating"</span>, <span class="st">"Reviews"</span>, <span class="st">"Sales"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Rating   Reviews     Sales
Rating  1.0000000 0.1533303 0.1289032
Reviews 0.1533303 1.0000000 0.6646022
Sales   0.1289032 0.6646022 1.0000000</code></pre>
</div>
</div>
<p>The correlation between the number of reviews and the number of sales is the strongest, with a correlation coefficient of 0.665. This means that an increase in sales is likely due to an increase in the number of reviews. The correlation between the number of reviews and the drug rating is weak, with a correlation coefficient of 0.153. The correlation between the number of sales and the drug rating is also weak, with a correlation coefficient of 0.129. This indicates that drug rating may not have a significant impact on the increase in number of sales.</p>
</section>
<section id="multiple-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="multiple-linear-regression">Multiple Linear Regression</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sales <span class="sc">~</span> Rating <span class="sc">+</span> Reviews, <span class="at">data =</span> data_RRS_noZero)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sales ~ Rating + Reviews, data = data_RRS_noZero)

Residuals:
    Min      1Q  Median      3Q     Max 
-6051.7  -809.4  -739.1  -540.8 15083.5 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -406.0586  1417.2841  -0.287    0.775    
Rating       236.9640   296.5141   0.799    0.425    
Reviews        2.5495     0.1336  19.087   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2700 on 477 degrees of freedom
Multiple R-squared:  0.4424,    Adjusted R-squared:  0.4401 
F-statistic: 189.3 on 2 and 477 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">1</span>), <span class="at">oma =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">0</span>))</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="GeneralAnalysis_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Although the model only explains 44% of the variation in sales (R<sup>2</sup> &gt; 0.7 indicates a good fit of the model), the linear regression model demonstrates that the impact of Reviews on sales is significant, whereas the impact of Rating on sales is not significant.</p>
</section>
<section id="route-visualisation-on-a-map" class="level3">
<h3 class="anchored" data-anchor-id="route-visualisation-on-a-map">Route Visualisation on a map</h3>
<p>I used Cannabis as an example. It doesn’t work well as NA, Unknown Location (I replaced it with NA), European Union, and World Wide cannot be shown on the map because they don’t have coordinates (latitude and longitude) information. Please see the warning below. If I remove them, then in most cases, the drugs are shipped domestically, which is not useful to show them on the map. Therefore, I used Sankey Diagram to do the data visualisation without putting them on the map.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#replace "Unknown Location" with NA, Using Cannabis as an example</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>Route_Cannabis <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Drug_Type_L<span class="sc">==</span><span class="st">"Cannabis"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Ship_From, Ship_To) <span class="sc">%&gt;%</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Ship_To =</span> <span class="fu">str_replace</span>(.<span class="sc">$</span>Ship_To, <span class="st">" - .*"</span>, <span class="st">""</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Ship_From =</span> <span class="fu">ifelse</span>(Ship_From <span class="sc">==</span> <span class="st">"Unknown Location"</span>, <span class="cn">NA</span>, Ship_From), <span class="at">Ship_To =</span> <span class="fu">ifelse</span>(Ship_To <span class="sc">==</span> <span class="st">"Unknown Location"</span>, <span class="cn">NA</span>, Ship_To)) <span class="sc">%&gt;%</span> </span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Ship_From, Ship_To) <span class="sc">%&gt;%</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Convert the country names to ISO3 codes:</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>Route_Cannabis<span class="sc">$</span>iso_from <span class="ot">&lt;-</span> <span class="fu">countrycode</span>(Route_Cannabis<span class="sc">$</span>Ship_From, <span class="st">"country.name"</span>, <span class="st">"iso3c"</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>Route_Cannabis<span class="sc">$</span>iso_to <span class="ot">&lt;-</span> <span class="fu">countrycode</span>(Route_Cannabis<span class="sc">$</span>Ship_To, <span class="st">"country.name"</span>, <span class="st">"iso3c"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Some values were not matched unambiguously: European Union, World Wide</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>world <span class="ot">&lt;-</span> <span class="fu">ne_countries</span>(<span class="at">scale =</span> <span class="st">"medium"</span>, <span class="at">returnclass =</span> <span class="st">"sf"</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>world<span class="sc">$</span>geometry <span class="ot">&lt;-</span> <span class="fu">st_make_valid</span>(world<span class="sc">$</span>geometry)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>coordinates <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">code =</span> world<span class="sc">$</span>iso_a3,</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">lon =</span> <span class="fu">as.numeric</span>(<span class="fu">st_coordinates</span>(<span class="fu">st_centroid</span>(world<span class="sc">$</span>geometry))[, <span class="dv">1</span>]),</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">lat =</span> <span class="fu">as.numeric</span>(<span class="fu">st_coordinates</span>(<span class="fu">st_centroid</span>(world<span class="sc">$</span>geometry))[, <span class="dv">2</span>])</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>Route_Cannabis <span class="ot">&lt;-</span> <span class="fu">merge</span>(Route_Cannabis, coordinates, <span class="at">by.x =</span> <span class="st">"iso_from"</span>, <span class="at">by.y =</span> <span class="st">"code"</span>)</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>Route_Cannabis <span class="ot">&lt;-</span> <span class="fu">merge</span>(Route_Cannabis, coordinates, <span class="at">by.x =</span> <span class="st">"iso_to"</span>, <span class="at">by.y =</span> <span class="st">"code"</span>, <span class="at">suffixes =</span> <span class="fu">c</span>(<span class="st">"_from"</span>, <span class="st">"_to"</span>))</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate the midpoints and angles for the labels:</span></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>Route_Cannabis<span class="sc">$</span>mid_lat <span class="ot">&lt;-</span> (Route_Cannabis<span class="sc">$</span>lat_from <span class="sc">+</span> Route_Cannabis<span class="sc">$</span>lat_to) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a>Route_Cannabis<span class="sc">$</span>mid_lon <span class="ot">&lt;-</span> (Route_Cannabis<span class="sc">$</span>lon_from <span class="sc">+</span> Route_Cannabis<span class="sc">$</span>lon_to) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a>Route_Cannabis<span class="sc">$</span>angle <span class="ot">&lt;-</span> <span class="fu">with</span>(Route_Cannabis, <span class="fu">atan2</span>(lat_to <span class="sc">-</span> lat_from, lon_to <span class="sc">-</span> lon_from) <span class="sc">*</span> <span class="dv">180</span> <span class="sc">/</span> pi)</span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a>map <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">borders</span>(<span class="st">"world"</span>, <span class="at">colour =</span> <span class="st">"gray50"</span>, <span class="at">fill =</span> <span class="st">"gray80"</span>) <span class="sc">+</span></span>
<span id="cb42-21"><a href="#cb42-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_fixed</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">180</span>, <span class="dv">180</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">60</span>, <span class="dv">90</span>), <span class="at">ratio =</span> <span class="fl">1.3</span>) <span class="sc">+</span></span>
<span id="cb42-22"><a href="#cb42-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb42-23"><a href="#cb42-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid =</span> <span class="fu">element_blank</span>())</span>
<span id="cb42-24"><a href="#cb42-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-25"><a href="#cb42-25" aria-hidden="true" tabindex="-1"></a>map <span class="sc">+</span> </span>
<span id="cb42-26"><a href="#cb42-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(</span>
<span id="cb42-27"><a href="#cb42-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> Route_Cannabis,</span>
<span id="cb42-28"><a href="#cb42-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> mid_lon, <span class="at">y =</span> mid_lat, <span class="at">label =</span> <span class="fu">paste</span>(Ship_From, <span class="st">"→"</span>, Ship_To), <span class="at">angle =</span> angle, <span class="at">col=</span><span class="st">'red'</span>),</span>
<span id="cb42-29"><a href="#cb42-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">2</span>,</span>
<span id="cb42-30"><a href="#cb42-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">hjust =</span> <span class="dv">0</span>,</span>
<span id="cb42-31"><a href="#cb42-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">vjust =</span> <span class="dv">0</span>,</span>
<span id="cb42-32"><a href="#cb42-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">nudge_x =</span> <span class="fl">0.5</span>,</span>
<span id="cb42-33"><a href="#cb42-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">nudge_y =</span> <span class="fl">0.5</span></span>
<span id="cb42-34"><a href="#cb42-34" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="GeneralAnalysis_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="sankey-diagram-routes-for-cannabis-interactive" class="level3">
<h3 class="anchored" data-anchor-id="sankey-diagram-routes-for-cannabis-interactive">Sankey Diagram: Routes for Cannabis (interactive)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>routes_type <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Ship_From, Ship_To, Drug_Type_L) <span class="sc">%&gt;%</span> </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Drug_Type_L,Ship_From, Ship_To) <span class="sc">%&gt;%</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Drug_Type_L, <span class="fu">desc</span>(count)) </span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> routes_type <span class="sc">%&gt;%</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Drug_Type_L <span class="sc">==</span> <span class="st">"Cannabis"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Ship_From,Ship_To,count)  </span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>nodes <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">name=</span><span class="fu">c</span>(df<span class="sc">$</span>Ship_From, df<span class="sc">$</span>Ship_To)) <span class="sc">%&gt;%</span> <span class="fu">unique</span>()</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>IDsource<span class="ot">=</span><span class="fu">match</span>(df<span class="sc">$</span>Ship_From, nodes<span class="sc">$</span>name)<span class="sc">-</span><span class="dv">1</span> </span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>IDtarget<span class="ot">=</span><span class="fu">match</span>(df<span class="sc">$</span>Ship_To, nodes<span class="sc">$</span>name)<span class="sc">-</span><span class="dv">1</span></span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a>ColourScal <span class="ot">=</span><span class="st">'d3.scaleOrdinal() .range(["#FDE725FF","#B4DE2CFF","#6DCD59FF","#35B779FF","#1F9E89FF","#26828EFF","#31688EFF","#3E4A89FF","#482878FF","#440154FF"])'</span></span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a><span class="fu">sankeyNetwork</span>(<span class="at">Links =</span> df, <span class="at">Nodes =</span> nodes,</span>
<span id="cb43-20"><a href="#cb43-20" aria-hidden="true" tabindex="-1"></a>              <span class="at">Source =</span> <span class="st">"IDsource"</span>, <span class="at">Target =</span> <span class="st">"IDtarget"</span>,</span>
<span id="cb43-21"><a href="#cb43-21" aria-hidden="true" tabindex="-1"></a>              <span class="at">Value =</span> <span class="st">"count"</span>, <span class="at">NodeID =</span> <span class="st">"name"</span>, </span>
<span id="cb43-22"><a href="#cb43-22" aria-hidden="true" tabindex="-1"></a>              <span class="at">sinksRight=</span><span class="cn">TRUE</span>, <span class="at">colourScale=</span>ColourScal, <span class="at">nodeWidth=</span><span class="dv">60</span>, <span class="at">fontSize=</span><span class="dv">20</span>, <span class="at">nodePadding=</span><span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="sankeyNetwork html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-e3c80bebd9c5b91f9738" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-e3c80bebd9c5b91f9738">{"x":{"links":{"source":[0,1,2,0,3,4,5,3,5,5,6,0,7,4,0,4,5,8,2,9,0,1,3],"target":[0,1,10,10,0,4,10,11,5,12,11,11,7,13,12,11,11,12,14,9,14,15,10],"value":[50,17,12,9,9,6,6,5,4,4,4,3,2,2,2,1,1,1,1,1,1,1,1]},"nodes":{"name":["United Kingdom","United States","Spain","Unknown Location","France","Germany","Netherlands","Australia","South Africa","Switzerland","European Union","World Wide",null,"European Union - France","European Union - United Kingdom","United States - United Kingdom"],"group":["United Kingdom","United States","Spain","Unknown Location","France","Germany","Netherlands","Australia","South Africa","Switzerland","European Union","World Wide",null,"European Union - France","European Union - United Kingdom","United States - United Kingdom"]},"options":{"NodeID":"name","NodeGroup":"name","LinkGroup":null,"colourScale":"d3.scaleOrdinal() .range([\"#FDE725FF\",\"#B4DE2CFF\",\"#6DCD59FF\",\"#35B779FF\",\"#1F9E89FF\",\"#26828EFF\",\"#31688EFF\",\"#3E4A89FF\",\"#482878FF\",\"#440154FF\"])","fontSize":20,"fontFamily":null,"nodeWidth":60,"nodePadding":20,"units":"","margin":{"top":null,"right":null,"bottom":null,"left":null},"iterations":32,"sinksRight":true}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>Again, I used Cannabis as an example. If you hover your mouse over the gray band, you can see the frequency of appearances of this transportation route in all drug-related advertisements. The wider the gray band, the more frequent the occurrence of this route. You can also move the blocks around if the words overlap. We can substitute Cannabis with other types of drugs and compare the differences. However, due to space limitations, we may not be able to include all the necessary diagrams in our publication. So, the following way of data visualisation might be more helpful.</p>
</section>
<section id="top-5-routes-for-each-type-of-drug-based-on-the-number-of-advertisements" class="level3">
<h3 class="anchored" data-anchor-id="top-5-routes-for-each-type-of-drug-based-on-the-number-of-advertisements">Top 5 routes for each type of drug based on the number of advertisements</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>routes_type_top5 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Ship_From, Ship_To, Drug_Type_L) <span class="sc">%&gt;%</span> </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Drug_Type_L, Ship_From, Ship_To) <span class="sc">%&gt;%</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Drug_Type_L, <span class="fu">desc</span>(count)) <span class="sc">%&gt;%</span> </span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Drug_Type_L) <span class="sc">%&gt;%</span> </span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">5</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Route =</span> <span class="fu">paste</span>(Ship_From, <span class="st">"→"</span>, Ship_To)) <span class="sc">%&gt;%</span> </span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Ship_From, <span class="sc">-</span>Ship_To) <span class="sc">%&gt;%</span></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Route =</span> <span class="fu">reorder_within</span>(Route, count, Drug_Type_L))</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(routes_type_top5, <span class="fu">aes</span>(<span class="at">x =</span> count, <span class="at">y =</span> Route, <span class="at">fill =</span> Drug_Type_L)) <span class="sc">+</span> </span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span> </span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>), <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.1</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Count"</span>, <span class="at">y =</span> <span class="st">"Route"</span>, <span class="at">fill =</span> <span class="st">"Drug Type"</span>) <span class="sc">+</span> </span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">name =</span> <span class="st">"Drug Type"</span>) <span class="sc">+</span> </span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_reordered</span>() <span class="sc">+</span> </span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"right"</span>, <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">0</span>, <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="GeneralAnalysis_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This diagram presents observations regarding the sending and destination locations for various drug types. The findings are as follows:</p>
<ul>
<li><p><strong>Benzodiazepines (Benzos):</strong> This drug type is primarily dispatched from the United States and the United Kingdom. The majority of shipments remain within their respective regions, while others are distributed globally.</p></li>
<li><p><strong>Cannabis:</strong> Cannabis is predominantly sent from the United Kingdom, the United States, and Spain. Within the United Kingdom, there is significant domestic circulation, whereas the United States mainly receives shipments for its own region.</p></li>
<li><p><strong>Dissociatives and Opioids:</strong> These two drug types are mainly dispatched from the United Kingdom, Netherlands, and the United States. They are distributed worldwide, although a portion is also sent to the sender’s own region, either the United Kingdom or the United States.</p></li>
<li><p><strong>Ecstasy:</strong> Ecstasy is shipped worldwide, with the Netherlands serving as the primary sending location. The circulation volumes in the United Kingdom and the United States are relatively smaller.</p></li>
<li><p><strong>Prescription Drugs:</strong> The diagram indicates that India is the leading sending location for prescription drugs, followed by Germany and the Netherlands. These drugs are sent to various destinations worldwide, including the European Union, the United States, and the United Kingdom.</p></li>
<li><p><strong>Psychedelics:</strong> The diagram suggests that the United States is the primary sending location for psychedelics, followed by the Netherlands. The destinations for psychedelics encompass the United States, the United Kingdom, and other global locations.</p></li>
<li><p><strong>Steroids:</strong> The majority of steroids originate from an undisclosed location, while the United Kingdom also plays a role in their distribution.</p></li>
<li><p><strong>Stimulants:</strong> The data reveals that the United States is the primary sending location for stimulants, followed by the Netherlands and Germany. These drugs are dispatched to various destinations worldwide, including the United States, the United Kingdom, and other locations.</p></li>
<li><p><strong>Weight Loss:</strong> Based on the available data, weight loss drugs are shipped from Poland.</p></li>
</ul>
<p>In summary, the sending and destination locations vary for different drug types. Some drugs circulate primarily within specific regions, while others have a global circulation. However, the distribution of vendors appears to be concentrated within the UK and EU regions, with sporadic presence of US-based vendors. These insights can help us understand the circulation trends and market demand for different drug types.</p>
</section>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section"></h3>
</section>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">Limitations</h2>
<p>The data sample size is limited, and the time frame for data collection spans 11 days. However, trading was ongoing during this period, and variables such as ratings, the number of sales and reviews were constantly changing. These changes could impact the statistical data and comparisons. The sales data collected on day 1 from one vendor may differ significantly from the data collected from another vendor on day 11. However, if both sets of data were collected on the same day, the differences in sales data might not be as significant.</p>
<!-- -->

</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    if (id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        for (let i = 0; i < 2; i++) {
          container.appendChild(note.children[i].cloneNode(true));
        }
        return container.innerHTML
      } else {
        return note.innerHTML;
      }
    } else {
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      try { hash = new URL(url).hash; } catch {}
      const id = hash.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note !== null) {
        try {
          const html = processXRef(id, note);
          instance.setContent(html);
        } finally {
          instance.enable();
          instance.show();
        }
      } else {
        // See if we can fetch this
        fetch(url.split('#')[0])
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.getElementById(id);
          console.log(htmlDoc.body.innerHTML);
          if (note !== null) {
            const html = processXRef(id, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb45" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "GeneralAnalysis"</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span><span class="co"> </span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: false</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a><span class="fu">## About the data</span></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>The dataset, scraped from <span class="co">[</span><span class="ot">Nemesis</span><span class="co">](http://nemesis555nchzn2dogee6mlc7xxgeeshqirmh3yzn4lo5cnd4s5a4yd.onion/)</span> between 1^st^ January to 11^th^ January, contains 1334 files comprising 607 posts on drug sales, 415 posts on fraud, 134 posts providing guides and tutorials on illegal activities, and other miscellaneous posts. In this analysis, we will focus solely on the drug sales-related posts.</span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>As the original documents were in text format, which made it difficult to carry out quantitative analysis, I cleaned the data and put them into a data frame. I then saved the data frame as a CSV file named "complete.csv".</span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a><span class="fu">## The payment method</span></span>
<span id="cb45-16"><a href="#cb45-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-17"><a href="#cb45-17" aria-hidden="true" tabindex="-1"></a>**Bitcoin and Monero accepted.** All items are listed as an **escrow**. The order process is as follows:</span>
<span id="cb45-18"><a href="#cb45-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-19"><a href="#cb45-19" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>After the buyer has placed an order, the vendor has 5 days to accept or reject the order.</span>
<span id="cb45-20"><a href="#cb45-20" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The buyer will get a full refund if the vendor doesn't accept the order within 5 days.</span>
<span id="cb45-21"><a href="#cb45-21" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>If the buyer doesn't want to wait 5 days, there will be a cancel button after 48 hours to cancel the order and get a full refund.</span>
<span id="cb45-22"><a href="#cb45-22" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>After the order got accepted, the vendor has 5 days to send it. The buyer can not cancel the order at this point.</span>
<span id="cb45-23"><a href="#cb45-23" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The buyer will get a full refund if the vendor doesn't send the order within 5 days.</span>
<span id="cb45-24"><a href="#cb45-24" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The buyer has 3 days to open a dispute if the order does not match the description.</span>
<span id="cb45-25"><a href="#cb45-25" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>After the order got finalized, the buyer can leave a review.</span>
<span id="cb45-26"><a href="#cb45-26" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>If you have any questions, leave a comment or create a post on our forum.</span>
<span id="cb45-27"><a href="#cb45-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-28"><a href="#cb45-28" aria-hidden="true" tabindex="-1"></a><span class="fu">## Load Packages and data</span></span>
<span id="cb45-29"><a href="#cb45-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-32"><a href="#cb45-32" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-33"><a href="#cb45-33" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: load-packages_data</span></span>
<span id="cb45-34"><a href="#cb45-34" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb45-35"><a href="#cb45-35" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb45-36"><a href="#cb45-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-37"><a href="#cb45-37" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb45-38"><a href="#cb45-38" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forcats)</span>
<span id="cb45-39"><a href="#cb45-39" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb45-40"><a href="#cb45-40" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidytext)</span>
<span id="cb45-41"><a href="#cb45-41" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraph)</span>
<span id="cb45-42"><a href="#cb45-42" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggraph)</span>
<span id="cb45-43"><a href="#cb45-43" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb45-44"><a href="#cb45-44" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb45-45"><a href="#cb45-45" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(geosphere)</span>
<span id="cb45-46"><a href="#cb45-46" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(countrycode)</span>
<span id="cb45-47"><a href="#cb45-47" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rnaturalearth)</span>
<span id="cb45-48"><a href="#cb45-48" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rnaturalearthdata)</span>
<span id="cb45-49"><a href="#cb45-49" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb45-50"><a href="#cb45-50" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lwgeom)</span>
<span id="cb45-51"><a href="#cb45-51" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggsankey)</span>
<span id="cb45-52"><a href="#cb45-52" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(networkD3)</span>
<span id="cb45-53"><a href="#cb45-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-54"><a href="#cb45-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-55"><a href="#cb45-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-56"><a href="#cb45-56" aria-hidden="true" tabindex="-1"></a>data  <span class="ot">&lt;-</span>  <span class="fu">read_csv</span>(<span class="st">"/Users/shihaitao/Documents/DarknetProject/Nemesis/complete.csv"</span>)</span>
<span id="cb45-57"><a href="#cb45-57" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-58"><a href="#cb45-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-59"><a href="#cb45-59" aria-hidden="true" tabindex="-1"></a><span class="fu">## The number of posts of each type of drugs (Top20)</span></span>
<span id="cb45-60"><a href="#cb45-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-63"><a href="#cb45-63" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-64"><a href="#cb45-64" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb45-65"><a href="#cb45-65" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb45-66"><a href="#cb45-66" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Drug_Type) <span class="sc">%&gt;%</span> </span>
<span id="cb45-67"><a href="#cb45-67" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb45-68"><a href="#cb45-68" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">separate</span>(Drug_Type, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"Drug_Type"</span>, <span class="st">"Drug_Sub"</span>), <span class="at">sep =</span> <span class="st">"  » "</span>) <span class="sc">%&gt;%</span></span>
<span id="cb45-69"><a href="#cb45-69" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(count)) <span class="sc">%&gt;%</span> </span>
<span id="cb45-70"><a href="#cb45-70" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(.,<span class="dv">20</span>)</span>
<span id="cb45-71"><a href="#cb45-71" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-72"><a href="#cb45-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-73"><a href="#cb45-73" aria-hidden="true" tabindex="-1"></a>Different types of drug are sold in Nemesis, namely, Cannabis, Dissociatives, Opioids, Steroids, Psychedelics, Stimulants, Prescription Drugs, Benzodiazepine (Benzos), Ecstasy, and others. Some drug type has specific subcategories associated with it. For example, under the drug type Cannabis, the subcategories include Buds and Flowers, Hash, and Shake. The "count" column represents the number of posts for each drug subcategory, indicating the frequency or popularity of each drug subcategory. For instance, the drug subcategory "Buds and Flowers" has a count of 103, and it has the highest number of posts among all the drug subcategories listed. Dissociatives (Ketamine), Ecstasy (XTC Pills), Steroids, and Stimulants (Cocaine, Amphetamine/Speed) also have significant counts, suggesting their popularity in the market.</span>
<span id="cb45-74"><a href="#cb45-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-75"><a href="#cb45-75" aria-hidden="true" tabindex="-1"></a><span class="fu">## The number of posts of each drug (Top20)</span></span>
<span id="cb45-76"><a href="#cb45-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-79"><a href="#cb45-79" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-80"><a href="#cb45-80" aria-hidden="true" tabindex="-1"></a><span class="co">#capitalise all the drug names and count </span></span>
<span id="cb45-81"><a href="#cb45-81" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>DrugName <span class="ot">&lt;-</span> <span class="fu">toupper</span>(data<span class="sc">$</span>DrugName)</span>
<span id="cb45-82"><a href="#cb45-82" aria-hidden="true" tabindex="-1"></a>item_counts <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(DrugName) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(count))</span>
<span id="cb45-83"><a href="#cb45-83" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(item_counts, <span class="dv">20</span>)</span>
<span id="cb45-84"><a href="#cb45-84" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-85"><a href="#cb45-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-86"><a href="#cb45-86" aria-hidden="true" tabindex="-1"></a>The data frame consists of the top 20 drug names mentioned in posts. The "count" column represents the number of posts for each drug. It can partly indicate the popularity of each drug. Based on the counts, we can see that LSD (n=14), Heroin (n=9), Gorilla Glue (n=7), Racemic Ketamine (n=7), and Xanax (n=7) have relatively higher counts, suggesting a higher level of discussion or interest in these drugs.</span>
<span id="cb45-87"><a href="#cb45-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-88"><a href="#cb45-88" aria-hidden="true" tabindex="-1"></a><span class="fu">## The brand name of the drugs for sale</span></span>
<span id="cb45-89"><a href="#cb45-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-90"><a href="#cb45-90" aria-hidden="true" tabindex="-1"></a>The table below shows each brand name and its number of occurrences, and it can be observed that MONSTERLAB and HYDROGURU are the brands with the highest number of occurrences. These two brands are not specific to any particular drug, but rather the names of the dealers. It seems that they have generated a certain brand effect, representing a guarantee of high-quality drugs.</span>
<span id="cb45-91"><a href="#cb45-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-94"><a href="#cb45-94" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-95"><a href="#cb45-95" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>BrandName <span class="ot">&lt;-</span> <span class="fu">toupper</span>(data<span class="sc">$</span>BrandName) </span>
<span id="cb45-96"><a href="#cb45-96" aria-hidden="true" tabindex="-1"></a>BrandName_Re_NA <span class="ot">&lt;-</span> data<span class="sc">$</span>BrandName[<span class="sc">!</span><span class="fu">is.na</span>(data<span class="sc">$</span>BrandName)] <span class="co">#remove NA</span></span>
<span id="cb45-97"><a href="#cb45-97" aria-hidden="true" tabindex="-1"></a>brand_counts <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">table</span>(BrandName_Re_NA))</span>
<span id="cb45-98"><a href="#cb45-98" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(brand_counts) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"BrandName"</span>, <span class="st">"Count"</span>)</span>
<span id="cb45-99"><a href="#cb45-99" aria-hidden="true" tabindex="-1"></a>brand_counts <span class="ot">&lt;-</span> brand_counts <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(Count))</span>
<span id="cb45-100"><a href="#cb45-100" aria-hidden="true" tabindex="-1"></a>brand_counts</span>
<span id="cb45-101"><a href="#cb45-101" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-102"><a href="#cb45-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-103"><a href="#cb45-103" aria-hidden="true" tabindex="-1"></a><span class="fu">### The brand name of XTC Pills</span></span>
<span id="cb45-104"><a href="#cb45-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-105"><a href="#cb45-105" aria-hidden="true" tabindex="-1"></a>Another interesting observation is that the brand name of XTC Pills may indicate the strength or purity of these drugs and also provide a guarantee of quality for buyers. For instance, ORANGE TESLA with the warning "strong, be careful!" (01025.txt) may harbour more potential strength compared to Pink Glitter Tesla, with the description "very clean and stimulating" (00307.txt). While almost all vendors selling XTC Pills highlight the "high quality" of their products, some emphasise that their XTC Pills have been "lab tested" (13 out of 42 posts) or "black light tested and reagent tested with Marquis and Froehd" (00458 and 01025). Such measures in place serve the primary role of ensuring top-notch quality and utmost safety.</span>
<span id="cb45-106"><a href="#cb45-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-109"><a href="#cb45-109" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-110"><a href="#cb45-110" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Drug_Type <span class="sc">==</span> <span class="st">"Ecstasy  » XTC Pills"</span><span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(BrandName)) <span class="sc">%&gt;%</span> </span>
<span id="cb45-111"><a href="#cb45-111" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Drug_Type, BrandName) <span class="sc">%&gt;%</span> </span>
<span id="cb45-112"><a href="#cb45-112" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>() </span>
<span id="cb45-113"><a href="#cb45-113" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-114"><a href="#cb45-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-117"><a href="#cb45-117" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-118"><a href="#cb45-118" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: FALSE</span></span>
<span id="cb45-119"><a href="#cb45-119" aria-hidden="true" tabindex="-1"></a><span class="co">#see the description of XTC Pills</span></span>
<span id="cb45-120"><a href="#cb45-120" aria-hidden="true" tabindex="-1"></a><span class="co">#view(data %&gt;% filter(Drug_Type =="Ecstasy  » XTC Pills") %&gt;% select(File_Name,BrandName,MainContent)) </span></span>
<span id="cb45-121"><a href="#cb45-121" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-122"><a href="#cb45-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-123"><a href="#cb45-123" aria-hidden="true" tabindex="-1"></a><span class="fu">### The availibility rate</span></span>
<span id="cb45-124"><a href="#cb45-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-127"><a href="#cb45-127" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-128"><a href="#cb45-128" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(data<span class="sc">$</span>Availablity <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb45-129"><a href="#cb45-129" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-130"><a href="#cb45-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-131"><a href="#cb45-131" aria-hidden="true" tabindex="-1"></a>It is worth mentioning that not all drugs available on the market are actually available on Nemesis Market. According to the dataset provided, the availability rate of drugs on the Nemesis Market is 95.87%. This may be due to reasons such as the drug being sold out or the drug vendors being on holiday.</span>
<span id="cb45-132"><a href="#cb45-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-133"><a href="#cb45-133" aria-hidden="true" tabindex="-1"></a><span class="fu">## Rating, Reviews and Sales</span></span>
<span id="cb45-134"><a href="#cb45-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-137"><a href="#cb45-137" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-138"><a href="#cb45-138" aria-hidden="true" tabindex="-1"></a><span class="co">#Get the Rating number from strings</span></span>
<span id="cb45-139"><a href="#cb45-139" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Rating <span class="ot">&lt;-</span> data<span class="sc">$</span>Rating <span class="sc">%&gt;%</span> </span>
<span id="cb45-140"><a href="#cb45-140" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_extract</span>(<span class="st">"</span><span class="sc">\\</span><span class="st">d+(</span><span class="sc">\\</span><span class="st">.</span><span class="sc">\\</span><span class="st">d+)?"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb45-141"><a href="#cb45-141" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.numeric</span>()</span>
<span id="cb45-142"><a href="#cb45-142" aria-hidden="true" tabindex="-1"></a><span class="co">#Select the columns that we need</span></span>
<span id="cb45-143"><a href="#cb45-143" aria-hidden="true" tabindex="-1"></a>data_RRS <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">select</span>(DrugName,Drug_Type,Vendor_Name, Rating,Reviews,Sales)</span>
<span id="cb45-144"><a href="#cb45-144" aria-hidden="true" tabindex="-1"></a>data_RRS <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Sales<span class="sc">==</span><span class="dv">0</span>)</span>
<span id="cb45-145"><a href="#cb45-145" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-146"><a href="#cb45-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-147"><a href="#cb45-147" aria-hidden="true" tabindex="-1"></a>127 drugs have never been sold, so it would be better to remove them before analysing the data.</span>
<span id="cb45-148"><a href="#cb45-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-151"><a href="#cb45-151" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-152"><a href="#cb45-152" aria-hidden="true" tabindex="-1"></a>data_RRS_noZero <span class="ot">&lt;-</span> data_RRS <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Sales<span class="sc">!=</span><span class="dv">0</span>)</span>
<span id="cb45-153"><a href="#cb45-153" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-154"><a href="#cb45-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-155"><a href="#cb45-155" aria-hidden="true" tabindex="-1"></a><span class="fu">### Let's see the statistical information about ratings, reviews, and sales.</span></span>
<span id="cb45-156"><a href="#cb45-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-159"><a href="#cb45-159" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-160"><a href="#cb45-160" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data_RRS_noZero[, <span class="fu">c</span>(<span class="st">"Rating"</span>, <span class="st">"Reviews"</span>, <span class="st">"Sales"</span>)])</span>
<span id="cb45-161"><a href="#cb45-161" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-162"><a href="#cb45-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-163"><a href="#cb45-163" aria-hidden="true" tabindex="-1"></a><span class="fu">### Grouped summary statistics: Calculate summary statistics for each type of drug.</span></span>
<span id="cb45-164"><a href="#cb45-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-167"><a href="#cb45-167" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-168"><a href="#cb45-168" aria-hidden="true" tabindex="-1"></a>group_Drug_Type <span class="ot">&lt;-</span> data_RRS_noZero <span class="sc">%&gt;%</span></span>
<span id="cb45-169"><a href="#cb45-169" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Drug_Type) <span class="sc">%&gt;%</span></span>
<span id="cb45-170"><a href="#cb45-170" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_rating =</span> <span class="fu">mean</span>(Rating),</span>
<span id="cb45-171"><a href="#cb45-171" aria-hidden="true" tabindex="-1"></a>            <span class="at">total_reviews =</span> <span class="fu">sum</span>(Reviews),</span>
<span id="cb45-172"><a href="#cb45-172" aria-hidden="true" tabindex="-1"></a>            <span class="at">toal_sales =</span> <span class="fu">sum</span>(Sales))</span>
<span id="cb45-173"><a href="#cb45-173" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-174"><a href="#cb45-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-175"><a href="#cb45-175" aria-hidden="true" tabindex="-1"></a>**Best-selling drug types (top 20)**</span>
<span id="cb45-176"><a href="#cb45-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-179"><a href="#cb45-179" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-180"><a href="#cb45-180" aria-hidden="true" tabindex="-1"></a>group_Drug_Type <span class="sc">%&gt;%</span> </span>
<span id="cb45-181"><a href="#cb45-181" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(toal_sales)) <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">20</span>)<span class="sc">%&gt;%</span> <span class="fu">select</span>(Drug_Type,toal_sales)</span>
<span id="cb45-182"><a href="#cb45-182" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-183"><a href="#cb45-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-184"><a href="#cb45-184" aria-hidden="true" tabindex="-1"></a>**Highest rated drug types (top 20)**</span>
<span id="cb45-185"><a href="#cb45-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-188"><a href="#cb45-188" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-189"><a href="#cb45-189" aria-hidden="true" tabindex="-1"></a>group_Drug_Type <span class="sc">%&gt;%</span> </span>
<span id="cb45-190"><a href="#cb45-190" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(mean_rating)) <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">20</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(Drug_Type, mean_rating)</span>
<span id="cb45-191"><a href="#cb45-191" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-192"><a href="#cb45-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-193"><a href="#cb45-193" aria-hidden="true" tabindex="-1"></a>**Types of drugs that get the most reviews (top 20)**</span>
<span id="cb45-194"><a href="#cb45-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-197"><a href="#cb45-197" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-198"><a href="#cb45-198" aria-hidden="true" tabindex="-1"></a>group_Drug_Type <span class="sc">%&gt;%</span> </span>
<span id="cb45-199"><a href="#cb45-199" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">desc</span>(total_reviews)) <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">20</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(Drug_Type, total_reviews)</span>
<span id="cb45-200"><a href="#cb45-200" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-201"><a href="#cb45-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-202"><a href="#cb45-202" aria-hidden="true" tabindex="-1"></a><span class="fu">### Grouped summary statistics: Calculate summary statistics for Vendors.</span></span>
<span id="cb45-203"><a href="#cb45-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-206"><a href="#cb45-206" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-207"><a href="#cb45-207" aria-hidden="true" tabindex="-1"></a>group_Vendor <span class="ot">&lt;-</span> data_RRS_noZero <span class="sc">%&gt;%</span></span>
<span id="cb45-208"><a href="#cb45-208" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Vendor_Name) <span class="sc">%&gt;%</span></span>
<span id="cb45-209"><a href="#cb45-209" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_reviews =</span> <span class="fu">sum</span>(Reviews),</span>
<span id="cb45-210"><a href="#cb45-210" aria-hidden="true" tabindex="-1"></a>            <span class="at">total_sales =</span> <span class="fu">sum</span>(Sales))</span>
<span id="cb45-211"><a href="#cb45-211" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-212"><a href="#cb45-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-213"><a href="#cb45-213" aria-hidden="true" tabindex="-1"></a>**Top 10 vendors based on sales**</span>
<span id="cb45-214"><a href="#cb45-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-217"><a href="#cb45-217" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-218"><a href="#cb45-218" aria-hidden="true" tabindex="-1"></a>group_Vendor <span class="sc">%&gt;%</span> </span>
<span id="cb45-219"><a href="#cb45-219" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_sales)) <span class="sc">%&gt;%</span> </span>
<span id="cb45-220"><a href="#cb45-220" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Vendor_Name,total_sales) <span class="sc">%&gt;%</span> </span>
<span id="cb45-221"><a href="#cb45-221" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span>
<span id="cb45-222"><a href="#cb45-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-223"><a href="#cb45-223" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-224"><a href="#cb45-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-225"><a href="#cb45-225" aria-hidden="true" tabindex="-1"></a>**Bottom 10 vendors (excluding those who never sold anything) based on sales**</span>
<span id="cb45-226"><a href="#cb45-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-229"><a href="#cb45-229" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-230"><a href="#cb45-230" aria-hidden="true" tabindex="-1"></a>group_Vendor <span class="sc">%&gt;%</span> </span>
<span id="cb45-231"><a href="#cb45-231" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_sales)) <span class="sc">%&gt;%</span> </span>
<span id="cb45-232"><a href="#cb45-232" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Vendor_Name,total_sales) <span class="sc">%&gt;%</span> </span>
<span id="cb45-233"><a href="#cb45-233" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tail</span>(<span class="dv">10</span>)</span>
<span id="cb45-234"><a href="#cb45-234" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-235"><a href="#cb45-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-236"><a href="#cb45-236" aria-hidden="true" tabindex="-1"></a>By comparing sales figures, we can identify that the top 10 sellers are SocialPharma (103577), maurelius(101537), MicroDroper(65912), queenofcannabis(58002), PingPongUK(44556), discover(44148), DrRelax(40992), TorDrug(39424), drugstar(36168), and straightfromnl(35666). The numbers in the parenthesis are sales on this platform. On the other hand, yodiweed(5), BSPLLC(3), kings(3), shinyflakes(3), OliverTwiztt(2), POPEYE_GERMANY(2), DoctorPotenz(1), Grüneapotheke(1), Replicagod(1), UKnarcotics(1) are the newcomers or less established sellers.</span>
<span id="cb45-237"><a href="#cb45-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-238"><a href="#cb45-238" aria-hidden="true" tabindex="-1"></a>We can further examine their advertising, returns policies, and self-introductions to understand why some sellers' products are more popular and in what ways they gain the trust of buyers.</span>
<span id="cb45-239"><a href="#cb45-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-242"><a href="#cb45-242" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-243"><a href="#cb45-243" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Vendor_Name<span class="sc">==</span><span class="st">"SocialPharma"</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(File_Name, Drug_Type, MainContent,Refund,Review))</span>
<span id="cb45-244"><a href="#cb45-244" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-245"><a href="#cb45-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-246"><a href="#cb45-246" aria-hidden="true" tabindex="-1"></a>The highest-selling vendor is called SocialPharma (filename: 00132, 00373, 00483, 00519, 00520, 00721, 00923, 01107), and they primarily sell two types of drugs, namely Benzodiazepine (Benzos) and Opioids. Only Oxycodone is shipped from the United Kingdom to worldwide destinations, and it is marked as "non-refundable/non-reshipable." The other products he sells, namely Zopiclone, Diazepam (Valium), Dihydrocodeine, Codeine, and Tramadol, are sold locally in the UK and have corresponding return and exchange policies. The vendor is a self-employed because he always refers to himself with "me" instead of "us".</span>
<span id="cb45-247"><a href="#cb45-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-248"><a href="#cb45-248" aria-hidden="true" tabindex="-1"></a>Surprisingly, his drug descriptions are often limited to just two lines, specifying the quantity and strength, without mentioning the quality of the products. Similarly, his return and exchange policies are quite brief. He offers either a reshipment or a 50% refund based on the buyer's purchase time and his own perception of the buyer's trustworthiness.</span>
<span id="cb45-249"><a href="#cb45-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-250"><a href="#cb45-250" aria-hidden="true" tabindex="-1"></a>Therefore, we can assume that the trust generated by the high ratings (all five stars) and a large number of reviews no longer requires him to go through the trouble of describing the product and building trust. In a way, the rating system and sales data have established trust that surpasses the need for product descriptions themselves. Another explanation could be attributed to the types of drugs they sell. Most of these drugs are sold in tablets, which gives limited room for detailed descriptions. This is in stark contrast to vendors selling Cannabis.</span>
<span id="cb45-251"><a href="#cb45-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-254"><a href="#cb45-254" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-255"><a href="#cb45-255" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Vendor_Name<span class="sc">==</span><span class="st">"maurelius"</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(File_Name, Drug_Type, MainContent,Refund,Review))</span>
<span id="cb45-256"><a href="#cb45-256" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-257"><a href="#cb45-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-258"><a href="#cb45-258" aria-hidden="true" tabindex="-1"></a>The second-largest vendor in terms of sales is named Maurelius (Filenames: 00028, 00137, 00497, 00498, 00544, 00550, 00553, 00554, 01168, 01170, 01206, 01227, 01240, 01249, 01250, 01253). They specialize in selling Cannabis (Shake, Hash, and Buds and Flowers) with detailed descriptions. **Tetrahydrocannabinol (THC)** level is generally provided as an indicator for potency. Numerous paragraphs are dedicated to describing the aroma and taste of each Cannabis product. For example, when describing Afghan Kush, the aroma and taste of this strain are mentioned three times.</span>
<span id="cb45-259"><a href="#cb45-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-260"><a href="#cb45-260" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; The aroma of this medical marijuana strain will be like a mango orange farm with a pinch of funky odor. The taste of this strain is not at all harsh. This will have a bland and fruity taste. (01253, Pos. 35-37)</span></span>
<span id="cb45-261"><a href="#cb45-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-262"><a href="#cb45-262" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Flavors\</span></span>
<span id="cb45-263"><a href="#cb45-263" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Herbal, Pine, Spicy, Sweet, Woody\</span></span>
<span id="cb45-264"><a href="#cb45-264" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Aromas\</span></span>
<span id="cb45-265"><a href="#cb45-265" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Earthy, Floral, Kush, Pungent, Spicy, Sweet (01253, Pos. 47-50)</span></span>
<span id="cb45-266"><a href="#cb45-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-267"><a href="#cb45-267" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Aroma</span></span>
<span id="cb45-268"><a href="#cb45-268" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb45-269"><a href="#cb45-269" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; As is the case with pretty much every single strain from the Hindu Kush mountain range, the primary aroma of the Afghan Kush strain is one of hash.</span></span>
<span id="cb45-270"><a href="#cb45-270" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb45-271"><a href="#cb45-271" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Dense, powdery, and just a little bit spicy, this strain smells like walking into a familiar and friendly hash pipe shop in the Middle East or West India.</span></span>
<span id="cb45-272"><a href="#cb45-272" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb45-273"><a href="#cb45-273" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; There is sweetness there, but the overwhelming characteristic of the aroma is one of dankness and pleasant hash.</span></span>
<span id="cb45-274"><a href="#cb45-274" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb45-275"><a href="#cb45-275" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Flavor</span></span>
<span id="cb45-276"><a href="#cb45-276" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb45-277"><a href="#cb45-277" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; The overwhelming quality of the taste of the Afghan Kush smoke is one of sweet hash. It is pretty similar to its aroma, though, with a few key differences that help set it apart.</span></span>
<span id="cb45-278"><a href="#cb45-278" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb45-279"><a href="#cb45-279" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Instead of the intense spiciness that you'd expect after walking nearby any Afghan Kush bud, the leading quality is one of dank hash. As soon as it hits your tongue, you feel almost overpowered by the taste of hashish.</span></span>
<span id="cb45-280"><a href="#cb45-280" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb45-281"><a href="#cb45-281" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; In a way, Afghan Kush tastes like a real marijuana experience -- that quintessential flavor quality that makes smoking marijuana what it is. (01253, Pos. 85-100)</span></span>
<span id="cb45-282"><a href="#cb45-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-283"><a href="#cb45-283" aria-hidden="true" tabindex="-1"></a>Furthermore, the heritage/hybrid of Cannabis is also an important aspect that vendors want to emphasise to highlight the rarity and effects of their products. For example:</span>
<span id="cb45-284"><a href="#cb45-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-285"><a href="#cb45-285" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Alien Cookies is an evenly balanced hybrid (50% sativa/50% indica) strain created through a cross of the popular Alien Dawg X Girl Scout Cookies strains. This bud is incredibly rare to find, but totally worth it every time because of its flawless combination of its parents' effects. (01240, Pos. 27-30)</span></span>
<span id="cb45-286"><a href="#cb45-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-287"><a href="#cb45-287" aria-hidden="true" tabindex="-1"></a>The effects of different drugs on the body reveals several patterns:</span>
<span id="cb45-288"><a href="#cb45-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-289"><a href="#cb45-289" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>Social Behavior and Creativity: Individuals who seek these drugs for their psychotropic effects may seek to experience heightened sociability, amplified ethusiasm and to facilitate creative endeavors.</span>
<span id="cb45-290"><a href="#cb45-290" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>Euphoria and Blissful Sensations: These effects may contribute to a sense of happiness, cheerfulness, and laughter, thereby attracting individuals seeking positive emotional experiences.</span>
<span id="cb45-291"><a href="#cb45-291" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>Relaxation and Body Buzz: This combination of physical relaxation and elevated mood may be appealing to individuals seeking stress relief, tranquility, and a soothing experience.</span>
<span id="cb45-292"><a href="#cb45-292" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>Medicinal Benefits: Individuals may turn to these drugs for potential therapeutic effects.</span>
<span id="cb45-293"><a href="#cb45-293" aria-hidden="true" tabindex="-1"></a><span class="ss">5.  </span>Sleep and Sedation: Some individuals may seek these drugs to aid with sleep-related issues or relaxation before bedtime.</span>
<span id="cb45-294"><a href="#cb45-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-295"><a href="#cb45-295" aria-hidden="true" tabindex="-1"></a>**Other ways to attract purchase:**</span>
<span id="cb45-296"><a href="#cb45-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-297"><a href="#cb45-297" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>Being frankly about the side effects: while dry mouth and dry eyes are often mentioned in the posts, medical adverse reactions are listed. For example,</span>
<span id="cb45-298"><a href="#cb45-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-299"><a href="#cb45-299" aria-hidden="true" tabindex="-1"></a><span class="at">    &gt; ADVERSE REACTIONS: Dry mouth, Dry eyes \</span></span>
<span id="cb45-300"><a href="#cb45-300" aria-hidden="true" tabindex="-1"></a><span class="at">    &gt; MEDICAL Depression, Insomnia, Stress, Cramps, Fatigue (00498, Pos. 59-60)</span></span>
<span id="cb45-301"><a href="#cb45-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-302"><a href="#cb45-302" aria-hidden="true" tabindex="-1"></a>    By providing honest and transparent information about the side effects and dangers of drugs, vendors can, to some extent, build trust. Potential users may be more inclined to work with vendors who are concerned about user safety. Vendors may feel that they have an ethical responsibility to provide accurate information to potential users to ensure that users are able to make informed decisions.</span>
<span id="cb45-303"><a href="#cb45-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-304"><a href="#cb45-304" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>The minimal negative side effects: for example, the vendor points out that Amnesia Haze is a sativa strain with minimal negative side effects compared to other sativa strains, as it doesn't induce dizziness, paranoia, anxiety, or nausea. The main drawback of Amnesia Haze is dry mouth (cotton mouth), which can be alleviated by staying hydrated before, during, and after cannabis consumption. (see 00497, Pos. 92-101)</span>
<span id="cb45-305"><a href="#cb45-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-306"><a href="#cb45-306" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Refund Policy: "If your order doesn't show up we can offer you 50% reship or refund of the original order. For years we used to reship 100% of the orders but unfortunately we live in a world where people take advantage of you and sometimes our clients lie when it comes to receiving orders. Please understand that we are here for money and we feel sorry that honnest men/women have to suffer the loss. Besides, you are buying weed, not vegetables. :)"</span></span>
<span id="cb45-307"><a href="#cb45-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-310"><a href="#cb45-310" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-311"><a href="#cb45-311" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb45-312"><a href="#cb45-312" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Vendor_Name<span class="sc">==</span><span class="st">"MicroDroper"</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(File_Name, Drug_Type, MainContent,Refund,Review))</span>
<span id="cb45-313"><a href="#cb45-313" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-314"><a href="#cb45-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-315"><a href="#cb45-315" aria-hidden="true" tabindex="-1"></a><span class="fu">### Bar plot of average rating per Drug_Type:</span></span>
<span id="cb45-316"><a href="#cb45-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-319"><a href="#cb45-319" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-320"><a href="#cb45-320" aria-hidden="true" tabindex="-1"></a>data_RRS_noZero <span class="sc">%&gt;%</span></span>
<span id="cb45-321"><a href="#cb45-321" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Drug_Type) <span class="sc">%&gt;%</span></span>
<span id="cb45-322"><a href="#cb45-322" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_rating =</span> <span class="fu">mean</span>(Rating)) <span class="sc">%&gt;%</span></span>
<span id="cb45-323"><a href="#cb45-323" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(mean_rating) <span class="sc">%&gt;%</span></span>
<span id="cb45-324"><a href="#cb45-324" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Drug_Type, mean_rating), <span class="at">y =</span> mean_rating, <span class="at">fill =</span> Drug_Type)) <span class="sc">+</span></span>
<span id="cb45-325"><a href="#cb45-325" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb45-326"><a href="#cb45-326" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Drug_Type, mean_rating), <span class="at">y =</span> mean_rating, <span class="at">label =</span> <span class="fu">round</span>(mean_rating, <span class="dv">2</span>)), <span class="at">vjust =</span> <span class="fl">0.6</span>, <span class="at">hjust=</span><span class="dv">0</span>,<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb45-327"><a href="#cb45-327" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add geom_text to display value labels</span></span>
<span id="cb45-328"><a href="#cb45-328" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb45-329"><a href="#cb45-329" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average Rating per Drug Type"</span>, <span class="at">y =</span> <span class="st">"Average Rating"</span>, <span class="at">x =</span> <span class="st">"Drug Type"</span>) <span class="sc">+</span></span>
<span id="cb45-330"><a href="#cb45-330" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>, <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>)) <span class="sc">+</span></span>
<span id="cb45-331"><a href="#cb45-331" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb45-332"><a href="#cb45-332" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-333"><a href="#cb45-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-334"><a href="#cb45-334" aria-hidden="true" tabindex="-1"></a><span class="fu">### Scatter plot of Sales vs. Review</span></span>
<span id="cb45-335"><a href="#cb45-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-338"><a href="#cb45-338" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-339"><a href="#cb45-339" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_RRS_noZero, <span class="fu">aes</span>(<span class="at">x =</span> Reviews, <span class="at">y =</span> Sales)) <span class="sc">+</span></span>
<span id="cb45-340"><a href="#cb45-340" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb45-341"><a href="#cb45-341" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb45-342"><a href="#cb45-342" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Sales vs. Reviews"</span>, <span class="at">x =</span> <span class="st">"Reviews"</span>, <span class="at">y =</span> <span class="st">"Sales"</span>) <span class="sc">+</span></span>
<span id="cb45-343"><a href="#cb45-343" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span>
<span id="cb45-344"><a href="#cb45-344" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-345"><a href="#cb45-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-346"><a href="#cb45-346" aria-hidden="true" tabindex="-1"></a><span class="fu">### correlation</span></span>
<span id="cb45-347"><a href="#cb45-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-350"><a href="#cb45-350" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-351"><a href="#cb45-351" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(data_RRS_noZero[, <span class="fu">c</span>(<span class="st">"Rating"</span>, <span class="st">"Reviews"</span>, <span class="st">"Sales"</span>)])</span>
<span id="cb45-352"><a href="#cb45-352" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-353"><a href="#cb45-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-354"><a href="#cb45-354" aria-hidden="true" tabindex="-1"></a>The correlation between the number of reviews and the number of sales is the strongest, with a correlation coefficient of 0.665. This means that an increase in sales is likely due to an increase in the number of reviews. The correlation between the number of reviews and the drug rating is weak, with a correlation coefficient of 0.153. The correlation between the number of sales and the drug rating is also weak, with a correlation coefficient of 0.129. This indicates that drug rating may not have a significant impact on the increase in number of sales.</span>
<span id="cb45-355"><a href="#cb45-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-356"><a href="#cb45-356" aria-hidden="true" tabindex="-1"></a><span class="fu">### Multiple Linear Regression</span></span>
<span id="cb45-357"><a href="#cb45-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-360"><a href="#cb45-360" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-361"><a href="#cb45-361" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sales <span class="sc">~</span> Rating <span class="sc">+</span> Reviews, <span class="at">data =</span> data_RRS_noZero)</span>
<span id="cb45-362"><a href="#cb45-362" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span>
<span id="cb45-363"><a href="#cb45-363" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">1</span>), <span class="at">oma =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">0</span>))</span>
<span id="cb45-364"><a href="#cb45-364" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model)</span>
<span id="cb45-365"><a href="#cb45-365" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-366"><a href="#cb45-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-367"><a href="#cb45-367" aria-hidden="true" tabindex="-1"></a>Although the model only explains 44% of the variation in sales (R^2^ <span class="sc">\&gt;</span> 0.7 indicates a good fit of the model), the linear regression model demonstrates that the impact of Reviews on sales is significant, whereas the impact of Rating on sales is not significant.</span>
<span id="cb45-368"><a href="#cb45-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-369"><a href="#cb45-369" aria-hidden="true" tabindex="-1"></a><span class="fu">### Route Visualisation on a map</span></span>
<span id="cb45-370"><a href="#cb45-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-371"><a href="#cb45-371" aria-hidden="true" tabindex="-1"></a>I used Cannabis as an example. It doesn't work well as NA, Unknown Location (I replaced it with NA), European Union, and World Wide cannot be shown on the map because they don't have coordinates (latitude and longitude) information. Please see the warning below. If I remove them, then in most cases, the drugs are shipped domestically, which is not useful to show them on the map. Therefore, I used Sankey Diagram to do the data visualisation without putting them on the map.</span>
<span id="cb45-372"><a href="#cb45-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-375"><a href="#cb45-375" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-376"><a href="#cb45-376" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb45-377"><a href="#cb45-377" aria-hidden="true" tabindex="-1"></a><span class="co">#replace "Unknown Location" with NA, Using Cannabis as an example</span></span>
<span id="cb45-378"><a href="#cb45-378" aria-hidden="true" tabindex="-1"></a>Route_Cannabis <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb45-379"><a href="#cb45-379" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Drug_Type_L<span class="sc">==</span><span class="st">"Cannabis"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb45-380"><a href="#cb45-380" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Ship_From, Ship_To) <span class="sc">%&gt;%</span></span>
<span id="cb45-381"><a href="#cb45-381" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Ship_To =</span> <span class="fu">str_replace</span>(.<span class="sc">$</span>Ship_To, <span class="st">" - .*"</span>, <span class="st">""</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb45-382"><a href="#cb45-382" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Ship_From =</span> <span class="fu">ifelse</span>(Ship_From <span class="sc">==</span> <span class="st">"Unknown Location"</span>, <span class="cn">NA</span>, Ship_From), <span class="at">Ship_To =</span> <span class="fu">ifelse</span>(Ship_To <span class="sc">==</span> <span class="st">"Unknown Location"</span>, <span class="cn">NA</span>, Ship_To)) <span class="sc">%&gt;%</span> </span>
<span id="cb45-383"><a href="#cb45-383" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Ship_From, Ship_To) <span class="sc">%&gt;%</span></span>
<span id="cb45-384"><a href="#cb45-384" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb45-385"><a href="#cb45-385" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb45-386"><a href="#cb45-386" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-387"><a href="#cb45-387" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-390"><a href="#cb45-390" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-391"><a href="#cb45-391" aria-hidden="true" tabindex="-1"></a><span class="co">#Convert the country names to ISO3 codes:</span></span>
<span id="cb45-392"><a href="#cb45-392" aria-hidden="true" tabindex="-1"></a>Route_Cannabis<span class="sc">$</span>iso_from <span class="ot">&lt;-</span> <span class="fu">countrycode</span>(Route_Cannabis<span class="sc">$</span>Ship_From, <span class="st">"country.name"</span>, <span class="st">"iso3c"</span>)</span>
<span id="cb45-393"><a href="#cb45-393" aria-hidden="true" tabindex="-1"></a>Route_Cannabis<span class="sc">$</span>iso_to <span class="ot">&lt;-</span> <span class="fu">countrycode</span>(Route_Cannabis<span class="sc">$</span>Ship_To, <span class="st">"country.name"</span>, <span class="st">"iso3c"</span>)</span>
<span id="cb45-394"><a href="#cb45-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-395"><a href="#cb45-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-396"><a href="#cb45-396" aria-hidden="true" tabindex="-1"></a>world <span class="ot">&lt;-</span> <span class="fu">ne_countries</span>(<span class="at">scale =</span> <span class="st">"medium"</span>, <span class="at">returnclass =</span> <span class="st">"sf"</span>)</span>
<span id="cb45-397"><a href="#cb45-397" aria-hidden="true" tabindex="-1"></a>world<span class="sc">$</span>geometry <span class="ot">&lt;-</span> <span class="fu">st_make_valid</span>(world<span class="sc">$</span>geometry)</span>
<span id="cb45-398"><a href="#cb45-398" aria-hidden="true" tabindex="-1"></a>coordinates <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb45-399"><a href="#cb45-399" aria-hidden="true" tabindex="-1"></a>  <span class="at">code =</span> world<span class="sc">$</span>iso_a3,</span>
<span id="cb45-400"><a href="#cb45-400" aria-hidden="true" tabindex="-1"></a>  <span class="at">lon =</span> <span class="fu">as.numeric</span>(<span class="fu">st_coordinates</span>(<span class="fu">st_centroid</span>(world<span class="sc">$</span>geometry))[, <span class="dv">1</span>]),</span>
<span id="cb45-401"><a href="#cb45-401" aria-hidden="true" tabindex="-1"></a>  <span class="at">lat =</span> <span class="fu">as.numeric</span>(<span class="fu">st_coordinates</span>(<span class="fu">st_centroid</span>(world<span class="sc">$</span>geometry))[, <span class="dv">2</span>])</span>
<span id="cb45-402"><a href="#cb45-402" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb45-403"><a href="#cb45-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-404"><a href="#cb45-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-405"><a href="#cb45-405" aria-hidden="true" tabindex="-1"></a>Route_Cannabis <span class="ot">&lt;-</span> <span class="fu">merge</span>(Route_Cannabis, coordinates, <span class="at">by.x =</span> <span class="st">"iso_from"</span>, <span class="at">by.y =</span> <span class="st">"code"</span>)</span>
<span id="cb45-406"><a href="#cb45-406" aria-hidden="true" tabindex="-1"></a>Route_Cannabis <span class="ot">&lt;-</span> <span class="fu">merge</span>(Route_Cannabis, coordinates, <span class="at">by.x =</span> <span class="st">"iso_to"</span>, <span class="at">by.y =</span> <span class="st">"code"</span>, <span class="at">suffixes =</span> <span class="fu">c</span>(<span class="st">"_from"</span>, <span class="st">"_to"</span>))</span>
<span id="cb45-407"><a href="#cb45-407" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-408"><a href="#cb45-408" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-409"><a href="#cb45-409" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate the midpoints and angles for the labels:</span></span>
<span id="cb45-410"><a href="#cb45-410" aria-hidden="true" tabindex="-1"></a>Route_Cannabis<span class="sc">$</span>mid_lat <span class="ot">&lt;-</span> (Route_Cannabis<span class="sc">$</span>lat_from <span class="sc">+</span> Route_Cannabis<span class="sc">$</span>lat_to) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb45-411"><a href="#cb45-411" aria-hidden="true" tabindex="-1"></a>Route_Cannabis<span class="sc">$</span>mid_lon <span class="ot">&lt;-</span> (Route_Cannabis<span class="sc">$</span>lon_from <span class="sc">+</span> Route_Cannabis<span class="sc">$</span>lon_to) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb45-412"><a href="#cb45-412" aria-hidden="true" tabindex="-1"></a>Route_Cannabis<span class="sc">$</span>angle <span class="ot">&lt;-</span> <span class="fu">with</span>(Route_Cannabis, <span class="fu">atan2</span>(lat_to <span class="sc">-</span> lat_from, lon_to <span class="sc">-</span> lon_from) <span class="sc">*</span> <span class="dv">180</span> <span class="sc">/</span> pi)</span>
<span id="cb45-413"><a href="#cb45-413" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-414"><a href="#cb45-414" aria-hidden="true" tabindex="-1"></a>map <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb45-415"><a href="#cb45-415" aria-hidden="true" tabindex="-1"></a>  <span class="fu">borders</span>(<span class="st">"world"</span>, <span class="at">colour =</span> <span class="st">"gray50"</span>, <span class="at">fill =</span> <span class="st">"gray80"</span>) <span class="sc">+</span></span>
<span id="cb45-416"><a href="#cb45-416" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_fixed</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">180</span>, <span class="dv">180</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">60</span>, <span class="dv">90</span>), <span class="at">ratio =</span> <span class="fl">1.3</span>) <span class="sc">+</span></span>
<span id="cb45-417"><a href="#cb45-417" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb45-418"><a href="#cb45-418" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid =</span> <span class="fu">element_blank</span>())</span>
<span id="cb45-419"><a href="#cb45-419" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-420"><a href="#cb45-420" aria-hidden="true" tabindex="-1"></a>map <span class="sc">+</span> </span>
<span id="cb45-421"><a href="#cb45-421" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(</span>
<span id="cb45-422"><a href="#cb45-422" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> Route_Cannabis,</span>
<span id="cb45-423"><a href="#cb45-423" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> mid_lon, <span class="at">y =</span> mid_lat, <span class="at">label =</span> <span class="fu">paste</span>(Ship_From, <span class="st">"→"</span>, Ship_To), <span class="at">angle =</span> angle, <span class="at">col=</span><span class="st">'red'</span>),</span>
<span id="cb45-424"><a href="#cb45-424" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">2</span>,</span>
<span id="cb45-425"><a href="#cb45-425" aria-hidden="true" tabindex="-1"></a>    <span class="at">hjust =</span> <span class="dv">0</span>,</span>
<span id="cb45-426"><a href="#cb45-426" aria-hidden="true" tabindex="-1"></a>    <span class="at">vjust =</span> <span class="dv">0</span>,</span>
<span id="cb45-427"><a href="#cb45-427" aria-hidden="true" tabindex="-1"></a>    <span class="at">nudge_x =</span> <span class="fl">0.5</span>,</span>
<span id="cb45-428"><a href="#cb45-428" aria-hidden="true" tabindex="-1"></a>    <span class="at">nudge_y =</span> <span class="fl">0.5</span></span>
<span id="cb45-429"><a href="#cb45-429" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb45-430"><a href="#cb45-430" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-431"><a href="#cb45-431" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-432"><a href="#cb45-432" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-433"><a href="#cb45-433" aria-hidden="true" tabindex="-1"></a><span class="fu">### Sankey Diagram: Routes for Cannabis (interactive)</span></span>
<span id="cb45-434"><a href="#cb45-434" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-437"><a href="#cb45-437" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-438"><a href="#cb45-438" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb45-439"><a href="#cb45-439" aria-hidden="true" tabindex="-1"></a>routes_type <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb45-440"><a href="#cb45-440" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Ship_From, Ship_To, Drug_Type_L) <span class="sc">%&gt;%</span> </span>
<span id="cb45-441"><a href="#cb45-441" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Drug_Type_L,Ship_From, Ship_To) <span class="sc">%&gt;%</span></span>
<span id="cb45-442"><a href="#cb45-442" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb45-443"><a href="#cb45-443" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Drug_Type_L, <span class="fu">desc</span>(count)) </span>
<span id="cb45-444"><a href="#cb45-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-445"><a href="#cb45-445" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> routes_type <span class="sc">%&gt;%</span></span>
<span id="cb45-446"><a href="#cb45-446" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Drug_Type_L <span class="sc">==</span> <span class="st">"Cannabis"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb45-447"><a href="#cb45-447" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Ship_From,Ship_To,count)  </span>
<span id="cb45-448"><a href="#cb45-448" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb45-449"><a href="#cb45-449" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-450"><a href="#cb45-450" aria-hidden="true" tabindex="-1"></a>nodes <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">name=</span><span class="fu">c</span>(df<span class="sc">$</span>Ship_From, df<span class="sc">$</span>Ship_To)) <span class="sc">%&gt;%</span> <span class="fu">unique</span>()</span>
<span id="cb45-451"><a href="#cb45-451" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb45-452"><a href="#cb45-452" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>IDsource<span class="ot">=</span><span class="fu">match</span>(df<span class="sc">$</span>Ship_From, nodes<span class="sc">$</span>name)<span class="sc">-</span><span class="dv">1</span> </span>
<span id="cb45-453"><a href="#cb45-453" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>IDtarget<span class="ot">=</span><span class="fu">match</span>(df<span class="sc">$</span>Ship_To, nodes<span class="sc">$</span>name)<span class="sc">-</span><span class="dv">1</span></span>
<span id="cb45-454"><a href="#cb45-454" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-455"><a href="#cb45-455" aria-hidden="true" tabindex="-1"></a>ColourScal <span class="ot">=</span><span class="st">'d3.scaleOrdinal() .range(["#FDE725FF","#B4DE2CFF","#6DCD59FF","#35B779FF","#1F9E89FF","#26828EFF","#31688EFF","#3E4A89FF","#482878FF","#440154FF"])'</span></span>
<span id="cb45-456"><a href="#cb45-456" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-457"><a href="#cb45-457" aria-hidden="true" tabindex="-1"></a><span class="fu">sankeyNetwork</span>(<span class="at">Links =</span> df, <span class="at">Nodes =</span> nodes,</span>
<span id="cb45-458"><a href="#cb45-458" aria-hidden="true" tabindex="-1"></a>              <span class="at">Source =</span> <span class="st">"IDsource"</span>, <span class="at">Target =</span> <span class="st">"IDtarget"</span>,</span>
<span id="cb45-459"><a href="#cb45-459" aria-hidden="true" tabindex="-1"></a>              <span class="at">Value =</span> <span class="st">"count"</span>, <span class="at">NodeID =</span> <span class="st">"name"</span>, </span>
<span id="cb45-460"><a href="#cb45-460" aria-hidden="true" tabindex="-1"></a>              <span class="at">sinksRight=</span><span class="cn">TRUE</span>, <span class="at">colourScale=</span>ColourScal, <span class="at">nodeWidth=</span><span class="dv">60</span>, <span class="at">fontSize=</span><span class="dv">20</span>, <span class="at">nodePadding=</span><span class="dv">20</span>)</span>
<span id="cb45-461"><a href="#cb45-461" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-462"><a href="#cb45-462" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-463"><a href="#cb45-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-464"><a href="#cb45-464" aria-hidden="true" tabindex="-1"></a>Again, I used Cannabis as an example. If you hover your mouse over the gray band, you can see the frequency of appearances of this transportation route in all drug-related advertisements. The wider the gray band, the more frequent the occurrence of this route. You can also move the blocks around if the words overlap. We can substitute Cannabis with other types of drugs and compare the differences. However, due to space limitations, we may not be able to include all the necessary diagrams in our publication. So, the following way of data visualisation might be more helpful.</span>
<span id="cb45-465"><a href="#cb45-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-466"><a href="#cb45-466" aria-hidden="true" tabindex="-1"></a><span class="fu">### Top 5 routes for each type of drug based on the number of advertisements</span></span>
<span id="cb45-467"><a href="#cb45-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-470"><a href="#cb45-470" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-471"><a href="#cb45-471" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb45-472"><a href="#cb45-472" aria-hidden="true" tabindex="-1"></a>routes_type_top5 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb45-473"><a href="#cb45-473" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Ship_From, Ship_To, Drug_Type_L) <span class="sc">%&gt;%</span> </span>
<span id="cb45-474"><a href="#cb45-474" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Drug_Type_L, Ship_From, Ship_To) <span class="sc">%&gt;%</span></span>
<span id="cb45-475"><a href="#cb45-475" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb45-476"><a href="#cb45-476" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Drug_Type_L, <span class="fu">desc</span>(count)) <span class="sc">%&gt;%</span> </span>
<span id="cb45-477"><a href="#cb45-477" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Drug_Type_L) <span class="sc">%&gt;%</span> </span>
<span id="cb45-478"><a href="#cb45-478" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">5</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb45-479"><a href="#cb45-479" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Route =</span> <span class="fu">paste</span>(Ship_From, <span class="st">"→"</span>, Ship_To)) <span class="sc">%&gt;%</span> </span>
<span id="cb45-480"><a href="#cb45-480" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Ship_From, <span class="sc">-</span>Ship_To) <span class="sc">%&gt;%</span></span>
<span id="cb45-481"><a href="#cb45-481" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Route =</span> <span class="fu">reorder_within</span>(Route, count, Drug_Type_L))</span>
<span id="cb45-482"><a href="#cb45-482" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-483"><a href="#cb45-483" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-484"><a href="#cb45-484" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(routes_type_top5, <span class="fu">aes</span>(<span class="at">x =</span> count, <span class="at">y =</span> Route, <span class="at">fill =</span> Drug_Type_L)) <span class="sc">+</span> </span>
<span id="cb45-485"><a href="#cb45-485" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span> </span>
<span id="cb45-486"><a href="#cb45-486" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>), <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.1</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb45-487"><a href="#cb45-487" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Count"</span>, <span class="at">y =</span> <span class="st">"Route"</span>, <span class="at">fill =</span> <span class="st">"Drug Type"</span>) <span class="sc">+</span> </span>
<span id="cb45-488"><a href="#cb45-488" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">name =</span> <span class="st">"Drug Type"</span>) <span class="sc">+</span> </span>
<span id="cb45-489"><a href="#cb45-489" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_reordered</span>() <span class="sc">+</span> </span>
<span id="cb45-490"><a href="#cb45-490" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb45-491"><a href="#cb45-491" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"right"</span>, <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">0</span>, <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>))</span>
<span id="cb45-492"><a href="#cb45-492" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-493"><a href="#cb45-493" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb45-494"><a href="#cb45-494" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-495"><a href="#cb45-495" aria-hidden="true" tabindex="-1"></a>This diagram presents observations regarding the sending and destination locations for various drug types. The findings are as follows:</span>
<span id="cb45-496"><a href="#cb45-496" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-497"><a href="#cb45-497" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Benzodiazepines (Benzos):** This drug type is primarily dispatched from the United States and the United Kingdom. The majority of shipments remain within their respective regions, while others are distributed globally.</span>
<span id="cb45-498"><a href="#cb45-498" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-499"><a href="#cb45-499" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Cannabis:** Cannabis is predominantly sent from the United Kingdom, the United States, and Spain. Within the United Kingdom, there is significant domestic circulation, whereas the United States mainly receives shipments for its own region.</span>
<span id="cb45-500"><a href="#cb45-500" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-501"><a href="#cb45-501" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Dissociatives and Opioids:** These two drug types are mainly dispatched from the United Kingdom, Netherlands, and the United States. They are distributed worldwide, although a portion is also sent to the sender's own region, either the United Kingdom or the United States.</span>
<span id="cb45-502"><a href="#cb45-502" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-503"><a href="#cb45-503" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Ecstasy:** Ecstasy is shipped worldwide, with the Netherlands serving as the primary sending location. The circulation volumes in the United Kingdom and the United States are relatively smaller.</span>
<span id="cb45-504"><a href="#cb45-504" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-505"><a href="#cb45-505" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Prescription Drugs:** The diagram indicates that India is the leading sending location for prescription drugs, followed by Germany and the Netherlands. These drugs are sent to various destinations worldwide, including the European Union, the United States, and the United Kingdom.</span>
<span id="cb45-506"><a href="#cb45-506" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-507"><a href="#cb45-507" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Psychedelics:** The diagram suggests that the United States is the primary sending location for psychedelics, followed by the Netherlands. The destinations for psychedelics encompass the United States, the United Kingdom, and other global locations.</span>
<span id="cb45-508"><a href="#cb45-508" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-509"><a href="#cb45-509" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Steroids:** The majority of steroids originate from an undisclosed location, while the United Kingdom also plays a role in their distribution.</span>
<span id="cb45-510"><a href="#cb45-510" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-511"><a href="#cb45-511" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Stimulants:** The data reveals that the United States is the primary sending location for stimulants, followed by the Netherlands and Germany. These drugs are dispatched to various destinations worldwide, including the United States, the United Kingdom, and other locations.</span>
<span id="cb45-512"><a href="#cb45-512" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-513"><a href="#cb45-513" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Weight Loss:** Based on the available data, weight loss drugs are shipped from Poland.</span>
<span id="cb45-514"><a href="#cb45-514" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-515"><a href="#cb45-515" aria-hidden="true" tabindex="-1"></a>In summary, the sending and destination locations vary for different drug types. Some drugs circulate primarily within specific regions, while others have a global circulation. However, the distribution of vendors appears to be concentrated within the UK and EU regions, with sporadic presence of US-based vendors. These insights can help us understand the circulation trends and market demand for different drug types.</span>
<span id="cb45-516"><a href="#cb45-516" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-517"><a href="#cb45-517" aria-hidden="true" tabindex="-1"></a><span class="fu">### </span></span>
<span id="cb45-518"><a href="#cb45-518" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-519"><a href="#cb45-519" aria-hidden="true" tabindex="-1"></a><span class="fu">## Limitations</span></span>
<span id="cb45-520"><a href="#cb45-520" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-521"><a href="#cb45-521" aria-hidden="true" tabindex="-1"></a>The data sample size is limited, and the time frame for data collection spans 11 days. However, trading was ongoing during this period, and variables such as ratings, the number of sales and reviews were constantly changing. These changes could impact the statistical data and comparisons. The sales data collected on day 1 from one vendor may differ significantly from the data collected from another vendor on day 11. However, if both sets of data were collected on the same day, the differences in sales data might not be as significant.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>