<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.146">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>GeneralAnalysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="GeneralAnalysisUpdate_files/libs/clipboard/clipboard.min.js"></script>
<script src="GeneralAnalysisUpdate_files/libs/quarto-html/quarto.js"></script>
<script src="GeneralAnalysisUpdate_files/libs/quarto-html/popper.min.js"></script>
<script src="GeneralAnalysisUpdate_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="GeneralAnalysisUpdate_files/libs/quarto-html/anchor.min.js"></script>
<link href="GeneralAnalysisUpdate_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="GeneralAnalysisUpdate_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="GeneralAnalysisUpdate_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="GeneralAnalysisUpdate_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="GeneralAnalysisUpdate_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">GeneralAnalysis</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="about-the-data" class="level2">
<h2 class="anchored" data-anchor-id="about-the-data">About the data</h2>
<p>The dataset, scraped from <a href="http://nemesis555nchzn2dogee6mlc7xxgeeshqirmh3yzn4lo5cnd4s5a4yd.onion/">Nemesis</a> between 1<sup>st</sup> January to 11<sup>th</sup> January, contains 1334 files comprising 607 posts on drug sales, 415 posts on fraud, 134 posts providing guides and tutorials on illegal activities, and other miscellaneous posts. In this analysis, we will focus solely on the drug sales-related posts.</p>
<p>As the original documents were in text format, which made it difficult to carry out quantitative analysis, I cleaned the data and put them into a data frame. I then saved the data frame as a CSV file named “complete.csv”.</p>
</section>
<section id="the-payment-method" class="level2">
<h2 class="anchored" data-anchor-id="the-payment-method">The payment method</h2>
<p><strong>Bitcoin and Monero accepted.</strong> All items are listed as an <strong>escrow</strong>. The order process is as follows:</p>
<ul>
<li>After the buyer has placed an order, the vendor has 5 days to accept or reject the order.</li>
<li>The buyer will get a full refund if the vendor doesn’t accept the order within 5 days.</li>
<li>If the buyer doesn’t want to wait 5 days, there will be a cancel button after 48 hours to cancel the order and get a full refund.</li>
<li>After the order got accepted, the vendor has 5 days to send it. The buyer can not cancel the order at this point.</li>
<li>The buyer will get a full refund if the vendor doesn’t send the order within 5 days.</li>
<li>The buyer has 3 days to open a dispute if the order does not match the description.</li>
<li>After the order got finalized, the buyer can leave a review.</li>
<li>If you have any questions, leave a comment or create a post on our forum.</li>
</ul>
</section>
<section id="load-packages-and-data" class="level2">
<h2 class="anchored" data-anchor-id="load-packages-and-data">Load Packages and data</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forcats)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidytext)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraph)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggraph)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(geosphere)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(countrycode)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rnaturalearth)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rnaturalearthdata)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lwgeom)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggsankey)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(networkD3)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>data  <span class="ot">&lt;-</span>  <span class="fu">read_csv</span>(<span class="st">"/Users/shihaitao/Documents/DarknetProject/Nemesis/complete.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="the-number-of-posts-of-each-type-of-drugs-top20" class="level2">
<h2 class="anchored" data-anchor-id="the-number-of-posts-of-each-type-of-drugs-top20">The number of posts of each type of drugs (Top20)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Drug_Type) <span class="sc">%&gt;%</span> </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">separate</span>(Drug_Type, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"Drug_Type"</span>, <span class="st">"Drug_Sub"</span>), <span class="at">sep =</span> <span class="st">"  » "</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(count)) <span class="sc">%&gt;%</span> </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(.,<span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 3
   Drug_Type               Drug_Sub               count
   &lt;chr&gt;                   &lt;chr&gt;                  &lt;int&gt;
 1 Cannabis                Buds and Flowers         103
 2 Dissociatives           Ketamine                  60
 3 Ecstasy                 XTC Pills                 42
 4 Steroids                &lt;NA&gt;                      32
 5 Stimulants              Cocaine                   32
 6 Prescription Drugs      &lt;NA&gt;                      29
 7 Stimulants              Amphetamine/Speed         29
 8 Opioids                 Oxycodone                 23
 9 Opioids                 Heroin                    20
10 Psychedelics            LSD                       20
11 Benzodiazepine (Benzos) Pills                     16
12 Stimulants              Adderall                  15
13 Stimulants              Methamphetamine (Meth)    15
14 Cannabis                Hash                      14
15 Benzodiazepine (Benzos) Diazepam (Valium)         13
16 Ecstasy                 MDMA                      13
17 Benzodiazepine (Benzos) Alprazolam (Xanax)         9
18 Psychedelics            DMT                        9
19 Cannabis                Shake                      8
20 Benzodiazepine (Benzos) Powder                     7</code></pre>
</div>
</div>
<p>Different types of drug are sold in Nemesis, namely, Cannabis, Dissociatives, Opioids, Steroids, Psychedelics, Stimulants, Prescription Drugs, Benzodiazepine (Benzos), Ecstasy, and others. Some drug type has specific subcategories associated with it. For example, under the drug type Cannabis, the subcategories include Buds and Flowers, Hash, and Shake. The “count” column represents the number of posts for each drug subcategory, indicating the frequency or popularity of each drug subcategory. For instance, the drug subcategory “Buds and Flowers” has a count of 103, and it has the highest number of posts among all the drug subcategories listed. Dissociatives (Ketamine), Ecstasy (XTC Pills), Steroids, and Stimulants (Cocaine, Amphetamine/Speed) also have significant counts, suggesting their popularity in the market.</p>
</section>
<section id="the-number-of-posts-of-each-drug-top20" class="level2">
<h2 class="anchored" data-anchor-id="the-number-of-posts-of-each-drug-top20">The number of posts of each drug (Top20)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#capitalise all the drug names and count </span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>DrugName <span class="ot">&lt;-</span> <span class="fu">toupper</span>(data<span class="sc">$</span>DrugName)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>item_counts <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(DrugName) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(count))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(item_counts, <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 2
   DrugName                                    count
   &lt;chr&gt;                                       &lt;int&gt;
 1 LSD                                            14
 2 HEROIN                                          9
 3 GORILLA GLUE                                    7
 4 RACEMIC KETAMINE                                7
 5 XANAX                                           7
 6 ADDERALL                                        6
 7 COKE                                            6
 8 KETAMINE S-ISOMER SUGAR                         6
 9 MDMA                                            6
10 OXYCODONE                                       6
11 SPEED PASTE                                     6
12 AMPHETAMINE PASTE                               5
13 CANNALOPE HAZE                                  5
14 COLOMBIAN COCAINE                               5
15 KETAMINE                                        5
16 KETAMINE-NEEDLES                                5
17 S-ISOMERE KETAMINE                              5
18 CLONAZEPAM                                      4
19 ORIGINAL LA PAZ, BOLIVIAN UNCUT RAW COCAINE     4
20 SOUR DIESEL                                     4</code></pre>
</div>
</div>
<p>The data frame consists of the top 20 drug names mentioned in posts. The “count” column represents the number of posts for each drug. It can partly indicate the popularity of each drug. Based on the counts, we can see that LSD (n=14), Heroin (n=9), Gorilla Glue (n=7), Racemic Ketamine (n=7), and Xanax (n=7) have relatively higher counts, suggesting a higher level of discussion or interest in these drugs.</p>
</section>
<section id="the-brand-name-of-the-drugs-for-sale" class="level2">
<h2 class="anchored" data-anchor-id="the-brand-name-of-the-drugs-for-sale">The brand name of the drugs for sale</h2>
<p>The table below shows each brand name and its number of occurrences, and it can be observed that MONSTERLAB and HYDROGURU are the brands with the highest number of occurrences. These two brands are not specific to any particular drug, but rather the names of the dealers. It seems that they have generated a certain brand effect, representing a guarantee of high-quality drugs.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>BrandName <span class="ot">&lt;-</span> <span class="fu">toupper</span>(data<span class="sc">$</span>BrandName) </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>BrandName_Re_NA <span class="ot">&lt;-</span> data<span class="sc">$</span>BrandName[<span class="sc">!</span><span class="fu">is.na</span>(data<span class="sc">$</span>BrandName)] <span class="co">#remove NA</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>brand_counts <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">table</span>(BrandName_Re_NA))</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(brand_counts) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"BrandName"</span>, <span class="st">"Count"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>brand_counts <span class="ot">&lt;-</span> brand_counts <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(Count))</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>brand_counts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 81 × 2
   BrandName     Count
   &lt;chr&gt;         &lt;int&gt;
 1 MONSTERLAB       21
 2 HYDROGURU        13
 3 CENFORCE          5
 4 BLUE PUNISHER     4
 5 KAMAGRA           4
 6 PFIZER            4
 7 VIDALISTA         4
 8 KETALAR           3
 9 MASERATI          3
10 PERCOCET          3
# ℹ 71 more rows</code></pre>
</div>
</div>
<section id="the-brand-name-of-xtc-pills" class="level3">
<h3 class="anchored" data-anchor-id="the-brand-name-of-xtc-pills">The brand name of XTC Pills</h3>
<p>Another interesting observation is that the brand name of XTC Pills may indicate the strength or purity of these drugs and also provide a guarantee of quality for buyers. For instance, ORANGE TESLA with the warning “strong, be careful!” (01025.txt) may harbour more potential strength compared to Pink Glitter Tesla, with the description “very clean and stimulating” (00307.txt). While almost all vendors selling XTC Pills highlight the “high quality” of their products, some emphasise that their XTC Pills have been “lab tested” (13 out of 42 posts) or “black light tested and reagent tested with Marquis and Froehd” (00458 and 01025). Such measures in place serve the primary role of ensuring top-notch quality and utmost safety.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Drug_Type <span class="sc">==</span> <span class="st">"Ecstasy  » XTC Pills"</span><span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(BrandName)) <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Drug_Type, BrandName) <span class="sc">%&gt;%</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 2
   Drug_Type            BrandName         
   &lt;chr&gt;                &lt;chr&gt;             
 1 Ecstasy  » XTC Pills BLUE PUNISHERS    
 2 Ecstasy  » XTC Pills PINK GLITTER TESLA
 3 Ecstasy  » XTC Pills PUNISHER          
 4 Ecstasy  » XTC Pills UFO               
 5 Ecstasy  » XTC Pills SUPERMAN          
 6 Ecstasy  » XTC Pills ORANGE TESLA      
 7 Ecstasy  » XTC Pills POKEMON           
 8 Ecstasy  » XTC Pills BLUE PUNISHER     
 9 Ecstasy  » XTC Pills HYDROGURU         
10 Ecstasy  » XTC Pills AUDI              
11 Ecstasy  » XTC Pills PANAMA            
12 Ecstasy  » XTC Pills TESLA             
13 Ecstasy  » XTC Pills SKULL FACE        
14 Ecstasy  » XTC Pills MB SKULL CANDY    
15 Ecstasy  » XTC Pills LOUIS VUITTON     
16 Ecstasy  » XTC Pills PURPLE DOMINO     
17 Ecstasy  » XTC Pills MASERATI          
18 Ecstasy  » XTC Pills FANTA             </code></pre>
</div>
</div>
</section>
<section id="the-availibility-rate" class="level3">
<h3 class="anchored" data-anchor-id="the-availibility-rate">The availibility rate</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(data<span class="sc">$</span>Availablity <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9587459</code></pre>
</div>
</div>
<p>It is worth mentioning that not all drugs available on the market are actually available on Nemesis Market. According to the dataset provided, the availability rate of drugs on the Nemesis Market is 95.87%. This may be due to reasons such as the drug being sold out or the drug vendors being on holiday.</p>
</section>
</section>
<section id="rating-reviews-and-sales" class="level2">
<h2 class="anchored" data-anchor-id="rating-reviews-and-sales">Rating, Reviews and Sales</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Get the Rating number from strings</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Rating <span class="ot">&lt;-</span> data<span class="sc">$</span>Rating <span class="sc">%&gt;%</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_extract</span>(<span class="st">"</span><span class="sc">\\</span><span class="st">d+(</span><span class="sc">\\</span><span class="st">.</span><span class="sc">\\</span><span class="st">d+)?"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.numeric</span>()</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Select the columns that we need</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>data_RRS <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">select</span>(DrugName,Drug_Type,Vendor_Name, Rating,Reviews,Sales)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>data_RRS <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Sales<span class="sc">==</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 127 × 6
   DrugName               Drug_Type             Vendor_Name Rating Reviews Sales
   &lt;chr&gt;                  &lt;chr&gt;                 &lt;chr&gt;        &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 RACEMIC KETAMINE       Dissociatives  » Ket… commission…      0       0     0
 2 NEEDLE KETAMINE        Dissociatives  » Ket… cocainecar…      0       0     0
 3 LIDOCAINE              Stimulants  » Lidoca… TreasureCr…      0       0     0
 4 SGT-263                Cannabis  » Syntheti… TreasureCr…      0       0     0
 5 4-MEO-PCP              Dissociatives  » Met… TreasureCr…      0       0     0
 6 METHOXPROPAMINE        Dissociatives  » Met… TreasureCr…      0       0     0
 7 MOTHOXPROPAMINE        Dissociatives  » Met… TreasureCr…      0       0     0
 8 RACEMIC KETAMINE       Dissociatives  » Ket… commission…      0       0     0
 9 METHAMPHETAMINE (METH) Stimulants  » Metham… TreasureCr…      0       0     0
10 OXYCODONE              Opioids  » Oxycodone  STUNNAGANG       0       0     0
# ℹ 117 more rows</code></pre>
</div>
</div>
<p>127 drugs have never been sold, so it would be better to remove them before analysing the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>data_RRS_noZero <span class="ot">&lt;-</span> data_RRS <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Sales<span class="sc">!=</span><span class="dv">0</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>data_RRS_noZero <span class="sc">%&gt;%</span> </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Vendor_Name) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(Sales)) <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 6
# Groups:   Vendor_Name [4]
   DrugName                           Drug_Type Vendor_Name Rating Reviews Sales
   &lt;chr&gt;                              &lt;chr&gt;     &lt;chr&gt;        &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 SUPER HASH POLLEN / AMNESIA POLM … Cannabis… TorDrug        5      1510 19712
 2 SUPER HASH / HOCE√ØMA RIF MOROCCO  Cannabis… TorDrug        5      1510 19712
 3 ETOMETHAZENE                       Opioids … MicroDroper    4.7     321 16478
 4 WHITE ISOTONITAZENE                Opioids … MicroDroper    4.7     321 16478
 5 SPECIAL PURPLE OPIOID              Opioids … MicroDroper    4.7     321 16478
 6 O-DSMT                             Opioids … MicroDroper    4.7     321 16478
 7 XANAX                              Benzodia… discover       4.9    1292 14720
 8 XANAX                              Benzodia… discover       4.9    1288 14715
 9 SUGAR KETAMINE                     Dissocia… discover       4.9    1286 14713
10 BUTANE HASH OIL (BHO)              Cannabis… Utopia         5       911 14697</code></pre>
</div>
</div>
<p>One important point here is that the ratings, reviews, and sales displayed on each post are not specific to the drug being sold itself, but rather pertain to the vendor. In other words, the ratings, reviews, and sales are a comprehensive evaluation of the vendor. From the data frame above, we can see the drugs being by the vendor are different, but the number of Rating, Reviews and Sales are the same. Since every vendor can sell different types of drugs, it would be statistically almost impossible to know the best-selling drug types, highest-rated drug types, or the types of drugs that receive the most reviews.</p>
<p>As previously indicated, the data collection period extends over a span of 11 days. It is important to note that trading activities were taking place throughout this duration, resulting in fluctuations in variables such as ratings, sales, and reviews. For instance, a comparison of the reviews and sales numbers for the vendor XANAX reveals minor disparities. Consequently, I retain the row containing the highest sales number as the definitive value for the rating, reviews, and sales of each vendor.</p>
<section id="the-statistical-information-about-ratings-reviews-and-sales." class="level3">
<h3 class="anchored" data-anchor-id="the-statistical-information-about-ratings-reviews-and-sales.">The statistical information about ratings, reviews, and sales.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>Vendor_RRS <span class="ot">&lt;-</span> data_RRS_noZero <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Vendor_Name,Rating,Reviews,Sales) <span class="sc">%&gt;%</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Vendor_Name) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(Sales)) <span class="sc">%&gt;%</span> </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Vendor_RRS[, <span class="fu">c</span>(<span class="st">"Rating"</span>, <span class="st">"Reviews"</span>, <span class="st">"Sales"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Rating         Reviews           Sales         
 Min.   :0.000   Min.   :   0.0   Min.   :    1.00  
 1st Qu.:4.700   1st Qu.:  20.0   1st Qu.:   39.25  
 Median :4.900   Median :  92.5   Median :  298.00  
 Mean   :4.726   Mean   : 417.6   Mean   : 1921.37  
 3rd Qu.:5.000   3rd Qu.: 368.8   3rd Qu.: 1217.00  
 Max.   :5.000   Max.   :5356.0   Max.   :19712.00  </code></pre>
</div>
</div>
</section>
<section id="scatter-plot-of-sales-vs.-review" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plot-of-sales-vs.-review">Scatter plot of Sales vs.&nbsp;Review</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Vendor_RRS, <span class="fu">aes</span>(<span class="at">x =</span> Reviews, <span class="at">y =</span> Sales)) <span class="sc">+</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Sales vs. Reviews"</span>, <span class="at">x =</span> <span class="st">"Reviews"</span>, <span class="at">y =</span> <span class="st">"Sales"</span>) <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="GeneralAnalysisUpdate_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="correlation" class="level3">
<h3 class="anchored" data-anchor-id="correlation">correlation</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(Vendor_RRS[, <span class="fu">c</span>(<span class="st">"Rating"</span>, <span class="st">"Reviews"</span>, <span class="st">"Sales"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Rating   Reviews     Sales
Rating  1.000000 0.1477360 0.1375880
Reviews 0.147736 1.0000000 0.6458619
Sales   0.137588 0.6458619 1.0000000</code></pre>
</div>
</div>
<p><strong>Top 10 vendors based on sales</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Vendor_RRS <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">arrange</span>(<span class="fu">desc</span>(Sales)), <span class="at">n=</span><span class="dv">10</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 4
   Vendor_Name     Rating Reviews Sales
   &lt;chr&gt;            &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 TorDrug            5      1510 19712
 2 MicroDroper        4.7     321 16478
 3 discover           4.9    1292 14720
 4 Utopia             5       911 14697
 5 YOURDEALER         5      1627 14179
 6 SocialPharma       5      5356 12956
 7 drugstar           5       928 12056
 8 queenofcannabis    5      2138 11606
 9 HighClass          5       818 10196
10 ozconnection       4.9    1441  9792</code></pre>
</div>
</div>
<!-- -->

</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    if (id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        for (let i = 0; i < 2; i++) {
          container.appendChild(note.children[i].cloneNode(true));
        }
        return container.innerHTML
      } else {
        return note.innerHTML;
      }
    } else {
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      try { hash = new URL(url).hash; } catch {}
      const id = hash.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note !== null) {
        try {
          const html = processXRef(id, note);
          instance.setContent(html);
        } finally {
          instance.enable();
          instance.show();
        }
      } else {
        // See if we can fetch this
        fetch(url.split('#')[0])
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.getElementById(id);
          console.log(htmlDoc.body.innerHTML);
          if (note !== null) {
            const html = processXRef(id, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb24" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "GeneralAnalysis"</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span><span class="co"> </span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: false</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="fu">## About the data</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>The dataset, scraped from <span class="co">[</span><span class="ot">Nemesis</span><span class="co">](http://nemesis555nchzn2dogee6mlc7xxgeeshqirmh3yzn4lo5cnd4s5a4yd.onion/)</span> between 1^st^ January to 11^th^ January, contains 1334 files comprising 607 posts on drug sales, 415 posts on fraud, 134 posts providing guides and tutorials on illegal activities, and other miscellaneous posts. In this analysis, we will focus solely on the drug sales-related posts.</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>As the original documents were in text format, which made it difficult to carry out quantitative analysis, I cleaned the data and put them into a data frame. I then saved the data frame as a CSV file named "complete.csv".</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a><span class="fu">## The payment method</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>**Bitcoin and Monero accepted.** All items are listed as an **escrow**. The order process is as follows:</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>After the buyer has placed an order, the vendor has 5 days to accept or reject the order.</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The buyer will get a full refund if the vendor doesn't accept the order within 5 days.</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>If the buyer doesn't want to wait 5 days, there will be a cancel button after 48 hours to cancel the order and get a full refund.</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>After the order got accepted, the vendor has 5 days to send it. The buyer can not cancel the order at this point.</span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The buyer will get a full refund if the vendor doesn't send the order within 5 days.</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The buyer has 3 days to open a dispute if the order does not match the description.</span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>After the order got finalized, the buyer can leave a review.</span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>If you have any questions, leave a comment or create a post on our forum.</span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a><span class="fu">## Load Packages and data</span></span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: load-packages_data</span></span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-37"><a href="#cb24-37" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb24-38"><a href="#cb24-38" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forcats)</span>
<span id="cb24-39"><a href="#cb24-39" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb24-40"><a href="#cb24-40" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidytext)</span>
<span id="cb24-41"><a href="#cb24-41" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraph)</span>
<span id="cb24-42"><a href="#cb24-42" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggraph)</span>
<span id="cb24-43"><a href="#cb24-43" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb24-44"><a href="#cb24-44" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb24-45"><a href="#cb24-45" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(geosphere)</span>
<span id="cb24-46"><a href="#cb24-46" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(countrycode)</span>
<span id="cb24-47"><a href="#cb24-47" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rnaturalearth)</span>
<span id="cb24-48"><a href="#cb24-48" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rnaturalearthdata)</span>
<span id="cb24-49"><a href="#cb24-49" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb24-50"><a href="#cb24-50" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lwgeom)</span>
<span id="cb24-51"><a href="#cb24-51" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggsankey)</span>
<span id="cb24-52"><a href="#cb24-52" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(networkD3)</span>
<span id="cb24-53"><a href="#cb24-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-54"><a href="#cb24-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-55"><a href="#cb24-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-56"><a href="#cb24-56" aria-hidden="true" tabindex="-1"></a>data  <span class="ot">&lt;-</span>  <span class="fu">read_csv</span>(<span class="st">"/Users/shihaitao/Documents/DarknetProject/Nemesis/complete.csv"</span>)</span>
<span id="cb24-57"><a href="#cb24-57" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-58"><a href="#cb24-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-59"><a href="#cb24-59" aria-hidden="true" tabindex="-1"></a><span class="fu">## The number of posts of each type of drugs (Top20)</span></span>
<span id="cb24-60"><a href="#cb24-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-63"><a href="#cb24-63" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb24-64"><a href="#cb24-64" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb24-65"><a href="#cb24-65" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb24-66"><a href="#cb24-66" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Drug_Type) <span class="sc">%&gt;%</span> </span>
<span id="cb24-67"><a href="#cb24-67" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb24-68"><a href="#cb24-68" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">separate</span>(Drug_Type, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"Drug_Type"</span>, <span class="st">"Drug_Sub"</span>), <span class="at">sep =</span> <span class="st">"  » "</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-69"><a href="#cb24-69" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(count)) <span class="sc">%&gt;%</span> </span>
<span id="cb24-70"><a href="#cb24-70" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(.,<span class="dv">20</span>)</span>
<span id="cb24-71"><a href="#cb24-71" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-72"><a href="#cb24-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-73"><a href="#cb24-73" aria-hidden="true" tabindex="-1"></a>Different types of drug are sold in Nemesis, namely, Cannabis, Dissociatives, Opioids, Steroids, Psychedelics, Stimulants, Prescription Drugs, Benzodiazepine (Benzos), Ecstasy, and others. Some drug type has specific subcategories associated with it. For example, under the drug type Cannabis, the subcategories include Buds and Flowers, Hash, and Shake. The "count" column represents the number of posts for each drug subcategory, indicating the frequency or popularity of each drug subcategory. For instance, the drug subcategory "Buds and Flowers" has a count of 103, and it has the highest number of posts among all the drug subcategories listed. Dissociatives (Ketamine), Ecstasy (XTC Pills), Steroids, and Stimulants (Cocaine, Amphetamine/Speed) also have significant counts, suggesting their popularity in the market.</span>
<span id="cb24-74"><a href="#cb24-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-75"><a href="#cb24-75" aria-hidden="true" tabindex="-1"></a><span class="fu">## The number of posts of each drug (Top20)</span></span>
<span id="cb24-76"><a href="#cb24-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-79"><a href="#cb24-79" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb24-80"><a href="#cb24-80" aria-hidden="true" tabindex="-1"></a><span class="co">#capitalise all the drug names and count </span></span>
<span id="cb24-81"><a href="#cb24-81" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>DrugName <span class="ot">&lt;-</span> <span class="fu">toupper</span>(data<span class="sc">$</span>DrugName)</span>
<span id="cb24-82"><a href="#cb24-82" aria-hidden="true" tabindex="-1"></a>item_counts <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(DrugName) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(count))</span>
<span id="cb24-83"><a href="#cb24-83" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(item_counts, <span class="dv">20</span>)</span>
<span id="cb24-84"><a href="#cb24-84" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-85"><a href="#cb24-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-86"><a href="#cb24-86" aria-hidden="true" tabindex="-1"></a>The data frame consists of the top 20 drug names mentioned in posts. The "count" column represents the number of posts for each drug. It can partly indicate the popularity of each drug. Based on the counts, we can see that LSD (n=14), Heroin (n=9), Gorilla Glue (n=7), Racemic Ketamine (n=7), and Xanax (n=7) have relatively higher counts, suggesting a higher level of discussion or interest in these drugs.</span>
<span id="cb24-87"><a href="#cb24-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-88"><a href="#cb24-88" aria-hidden="true" tabindex="-1"></a><span class="fu">## The brand name of the drugs for sale</span></span>
<span id="cb24-89"><a href="#cb24-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-90"><a href="#cb24-90" aria-hidden="true" tabindex="-1"></a>The table below shows each brand name and its number of occurrences, and it can be observed that MONSTERLAB and HYDROGURU are the brands with the highest number of occurrences. These two brands are not specific to any particular drug, but rather the names of the dealers. It seems that they have generated a certain brand effect, representing a guarantee of high-quality drugs.</span>
<span id="cb24-91"><a href="#cb24-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-94"><a href="#cb24-94" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb24-95"><a href="#cb24-95" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>BrandName <span class="ot">&lt;-</span> <span class="fu">toupper</span>(data<span class="sc">$</span>BrandName) </span>
<span id="cb24-96"><a href="#cb24-96" aria-hidden="true" tabindex="-1"></a>BrandName_Re_NA <span class="ot">&lt;-</span> data<span class="sc">$</span>BrandName[<span class="sc">!</span><span class="fu">is.na</span>(data<span class="sc">$</span>BrandName)] <span class="co">#remove NA</span></span>
<span id="cb24-97"><a href="#cb24-97" aria-hidden="true" tabindex="-1"></a>brand_counts <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">table</span>(BrandName_Re_NA))</span>
<span id="cb24-98"><a href="#cb24-98" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(brand_counts) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"BrandName"</span>, <span class="st">"Count"</span>)</span>
<span id="cb24-99"><a href="#cb24-99" aria-hidden="true" tabindex="-1"></a>brand_counts <span class="ot">&lt;-</span> brand_counts <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(Count))</span>
<span id="cb24-100"><a href="#cb24-100" aria-hidden="true" tabindex="-1"></a>brand_counts</span>
<span id="cb24-101"><a href="#cb24-101" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-102"><a href="#cb24-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-103"><a href="#cb24-103" aria-hidden="true" tabindex="-1"></a><span class="fu">### The brand name of XTC Pills</span></span>
<span id="cb24-104"><a href="#cb24-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-105"><a href="#cb24-105" aria-hidden="true" tabindex="-1"></a>Another interesting observation is that the brand name of XTC Pills may indicate the strength or purity of these drugs and also provide a guarantee of quality for buyers. For instance, ORANGE TESLA with the warning "strong, be careful!" (01025.txt) may harbour more potential strength compared to Pink Glitter Tesla, with the description "very clean and stimulating" (00307.txt). While almost all vendors selling XTC Pills highlight the "high quality" of their products, some emphasise that their XTC Pills have been "lab tested" (13 out of 42 posts) or "black light tested and reagent tested with Marquis and Froehd" (00458 and 01025). Such measures in place serve the primary role of ensuring top-notch quality and utmost safety.</span>
<span id="cb24-106"><a href="#cb24-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-109"><a href="#cb24-109" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb24-110"><a href="#cb24-110" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Drug_Type <span class="sc">==</span> <span class="st">"Ecstasy  » XTC Pills"</span><span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(BrandName)) <span class="sc">%&gt;%</span> </span>
<span id="cb24-111"><a href="#cb24-111" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Drug_Type, BrandName) <span class="sc">%&gt;%</span> </span>
<span id="cb24-112"><a href="#cb24-112" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>() </span>
<span id="cb24-113"><a href="#cb24-113" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-114"><a href="#cb24-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-117"><a href="#cb24-117" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb24-118"><a href="#cb24-118" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: FALSE</span></span>
<span id="cb24-119"><a href="#cb24-119" aria-hidden="true" tabindex="-1"></a><span class="co">#see the description of XTC Pills</span></span>
<span id="cb24-120"><a href="#cb24-120" aria-hidden="true" tabindex="-1"></a><span class="co">#view(data %&gt;% filter(Drug_Type =="Ecstasy  » XTC Pills") %&gt;% select(File_Name,BrandName,MainContent)) </span></span>
<span id="cb24-121"><a href="#cb24-121" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-122"><a href="#cb24-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-123"><a href="#cb24-123" aria-hidden="true" tabindex="-1"></a><span class="fu">### The availibility rate</span></span>
<span id="cb24-124"><a href="#cb24-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-127"><a href="#cb24-127" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb24-128"><a href="#cb24-128" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(data<span class="sc">$</span>Availablity <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb24-129"><a href="#cb24-129" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-130"><a href="#cb24-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-131"><a href="#cb24-131" aria-hidden="true" tabindex="-1"></a>It is worth mentioning that not all drugs available on the market are actually available on Nemesis Market. According to the dataset provided, the availability rate of drugs on the Nemesis Market is 95.87%. This may be due to reasons such as the drug being sold out or the drug vendors being on holiday.</span>
<span id="cb24-132"><a href="#cb24-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-133"><a href="#cb24-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-134"><a href="#cb24-134" aria-hidden="true" tabindex="-1"></a><span class="fu">## Rating, Reviews and Sales</span></span>
<span id="cb24-135"><a href="#cb24-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-138"><a href="#cb24-138" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb24-139"><a href="#cb24-139" aria-hidden="true" tabindex="-1"></a><span class="co">#Get the Rating number from strings</span></span>
<span id="cb24-140"><a href="#cb24-140" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Rating <span class="ot">&lt;-</span> data<span class="sc">$</span>Rating <span class="sc">%&gt;%</span> </span>
<span id="cb24-141"><a href="#cb24-141" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_extract</span>(<span class="st">"</span><span class="sc">\\</span><span class="st">d+(</span><span class="sc">\\</span><span class="st">.</span><span class="sc">\\</span><span class="st">d+)?"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb24-142"><a href="#cb24-142" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.numeric</span>()</span>
<span id="cb24-143"><a href="#cb24-143" aria-hidden="true" tabindex="-1"></a><span class="co">#Select the columns that we need</span></span>
<span id="cb24-144"><a href="#cb24-144" aria-hidden="true" tabindex="-1"></a>data_RRS <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">select</span>(DrugName,Drug_Type,Vendor_Name, Rating,Reviews,Sales)</span>
<span id="cb24-145"><a href="#cb24-145" aria-hidden="true" tabindex="-1"></a>data_RRS <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Sales<span class="sc">==</span><span class="dv">0</span>)</span>
<span id="cb24-146"><a href="#cb24-146" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-147"><a href="#cb24-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-148"><a href="#cb24-148" aria-hidden="true" tabindex="-1"></a>127 drugs have never been sold, so it would be better to remove them before analysing the data.</span>
<span id="cb24-149"><a href="#cb24-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-152"><a href="#cb24-152" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb24-153"><a href="#cb24-153" aria-hidden="true" tabindex="-1"></a>data_RRS_noZero <span class="ot">&lt;-</span> data_RRS <span class="sc">%&gt;%</span> </span>
<span id="cb24-154"><a href="#cb24-154" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Sales<span class="sc">!=</span><span class="dv">0</span>)</span>
<span id="cb24-155"><a href="#cb24-155" aria-hidden="true" tabindex="-1"></a>data_RRS_noZero <span class="sc">%&gt;%</span> </span>
<span id="cb24-156"><a href="#cb24-156" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Vendor_Name) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(Sales)) <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">10</span>)</span>
<span id="cb24-157"><a href="#cb24-157" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-158"><a href="#cb24-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-159"><a href="#cb24-159" aria-hidden="true" tabindex="-1"></a>One important point here is that the ratings, reviews, and sales displayed on each post are not specific to the drug being sold itself, but rather pertain to the vendor. In other words, the ratings, reviews, and sales are a comprehensive evaluation of the vendor. From the data frame above, we can see the drugs being by the vendor are different, but the number of Rating, Reviews and Sales are the same. Since every vendor can sell different types of drugs, it would be statistically almost impossible to know the best-selling drug types, highest-rated drug types, or the types of drugs that receive the most reviews.</span>
<span id="cb24-160"><a href="#cb24-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-161"><a href="#cb24-161" aria-hidden="true" tabindex="-1"></a>As previously indicated, the data collection period extends over a span of 11 days. It is important to note that trading activities were taking place throughout this duration, resulting in fluctuations in variables such as ratings, sales, and reviews. For instance, a comparison of the reviews and sales numbers for the vendor XANAX reveals minor disparities. Consequently, I retain the row containing the highest sales number as the definitive value for the rating, reviews, and sales of each vendor.</span>
<span id="cb24-162"><a href="#cb24-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-163"><a href="#cb24-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-164"><a href="#cb24-164" aria-hidden="true" tabindex="-1"></a><span class="fu">### The statistical information about ratings, reviews, and sales.</span></span>
<span id="cb24-165"><a href="#cb24-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-168"><a href="#cb24-168" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb24-169"><a href="#cb24-169" aria-hidden="true" tabindex="-1"></a>Vendor_RRS <span class="ot">&lt;-</span> data_RRS_noZero <span class="sc">%&gt;%</span> </span>
<span id="cb24-170"><a href="#cb24-170" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Vendor_Name,Rating,Reviews,Sales) <span class="sc">%&gt;%</span> </span>
<span id="cb24-171"><a href="#cb24-171" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Vendor_Name) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(Sales)) <span class="sc">%&gt;%</span> </span>
<span id="cb24-172"><a href="#cb24-172" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb24-173"><a href="#cb24-173" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() </span>
<span id="cb24-174"><a href="#cb24-174" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Vendor_RRS[, <span class="fu">c</span>(<span class="st">"Rating"</span>, <span class="st">"Reviews"</span>, <span class="st">"Sales"</span>)])</span>
<span id="cb24-175"><a href="#cb24-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-176"><a href="#cb24-176" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-177"><a href="#cb24-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-178"><a href="#cb24-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-179"><a href="#cb24-179" aria-hidden="true" tabindex="-1"></a><span class="fu">### Scatter plot of Sales vs. Review</span></span>
<span id="cb24-180"><a href="#cb24-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-183"><a href="#cb24-183" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb24-184"><a href="#cb24-184" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Vendor_RRS, <span class="fu">aes</span>(<span class="at">x =</span> Reviews, <span class="at">y =</span> Sales)) <span class="sc">+</span></span>
<span id="cb24-185"><a href="#cb24-185" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb24-186"><a href="#cb24-186" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb24-187"><a href="#cb24-187" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Sales vs. Reviews"</span>, <span class="at">x =</span> <span class="st">"Reviews"</span>, <span class="at">y =</span> <span class="st">"Sales"</span>) <span class="sc">+</span></span>
<span id="cb24-188"><a href="#cb24-188" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span>
<span id="cb24-189"><a href="#cb24-189" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-190"><a href="#cb24-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-191"><a href="#cb24-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-192"><a href="#cb24-192" aria-hidden="true" tabindex="-1"></a><span class="fu">### correlation</span></span>
<span id="cb24-193"><a href="#cb24-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-196"><a href="#cb24-196" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb24-197"><a href="#cb24-197" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(Vendor_RRS[, <span class="fu">c</span>(<span class="st">"Rating"</span>, <span class="st">"Reviews"</span>, <span class="st">"Sales"</span>)])</span>
<span id="cb24-198"><a href="#cb24-198" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-199"><a href="#cb24-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-200"><a href="#cb24-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-201"><a href="#cb24-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-202"><a href="#cb24-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-203"><a href="#cb24-203" aria-hidden="true" tabindex="-1"></a>**Top 10 vendors based on sales**</span>
<span id="cb24-204"><a href="#cb24-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-207"><a href="#cb24-207" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb24-208"><a href="#cb24-208" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Vendor_RRS <span class="sc">%&gt;%</span> </span>
<span id="cb24-209"><a href="#cb24-209" aria-hidden="true" tabindex="-1"></a>       <span class="fu">arrange</span>(<span class="fu">desc</span>(Sales)), <span class="at">n=</span><span class="dv">10</span>) </span>
<span id="cb24-210"><a href="#cb24-210" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-211"><a href="#cb24-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-212"><a href="#cb24-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-213"><a href="#cb24-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-214"><a href="#cb24-214" aria-hidden="true" tabindex="-1"></a></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>